import test from 'node:test';
import assert from 'node:assert/strict';
import {parseSquadDirectory,parseSquad,parseProgram,parseStarters,parseClubBoard,captureFifaHistory} from '../lib/enhancements.mjs';
test('squad discovery chooses the latest distinct completed call-up and rejects external targets',()=>{
 const row=(date,url)=>`<tr><td>${date}</td><td><a href="${url}">招集メンバーはこちら</a></td></tr>`;
 const rows=parseSquadDirectory('<table>'+row('10/1','/samuraiblue/cup/member.html')+row('10/5','/samuraiblue/cup/member.html')+row('9/28','/samuraiblue/previous/member.html')+row('11/17','/samuraiblue/future/member.html')+row('10/10','https://evil.test/')+'</table>','2026-10-11');assert.deepEqual(rows.map(r=>r.date),['2026-10-05','2026-09-28']);assert.ok(rows.every(r=>r.url.startsWith('https://www.jfa.jp/')));
});
test('official squad has positions, clubs, unique ids and a minimum usable roster',()=>{
 const rows=Array.from({length:11},(_,i)=>`<li><a href="/samuraiblue/member/player_${i}.html"><span class="name">${i+1} 選手 ${i}</span><span class="status">クラブ／国</span></a></li>`).join('');const data=parseSquad(`<div class="section-block"><h4>MF/FW</h4><div class="competition-member">${rows}</div></div>`);assert.equal(data.length,11);assert.equal(data[0].name,'選手 0');assert.equal(data[0].position,'MF/FW');assert.throws(()=>parseSquad('<html></html>'));
});
test('program distinguishes goalkeeper conceded count from goals, preserves zero, and sorts substitutions and goals',()=>{
 const player=(name,pos,stats)=>`<div class="player_card"><p class="name">${name}</p><p class="pos">${pos}</p><dl><dt>国際Aマッチ試合数</dt><dd>${stats}</dd></dl></div>`;const html='<p>2026年9月29日現在</p>'+player('GK選手','GK','29試合／-19得点')+player('FW選手','MF/FW','2試合／0得点')+`<div class="game_line left"><li><p class="timer">71'</p><p class="pointer">得点者</p></li></div><div class="modal_report"><div data-tablist="jp"><ul class="member_list"><li><p class="name">交代選手</p><p class="change">64' IN</p></li></ul></div></div>`;const data=parseProgram(html);assert.equal(data.asOf,'2026-09-29');assert.equal(data.players[0].goals,null);assert.equal(data.players[0].conceded,19);assert.equal(data.players[1].goals,0);assert.deepEqual(data.events.map(e=>e.kind),['交代 IN','得点']);
});
test('starter announcements retain publication date and both pitchers rather than predicting missing names',()=>{
 const data=parseStarters('<div class="contents"><h4>10月11日の予告先発投手</h4><div class="unit_starter_position"><div class="unit"><div class="team_left"><img alt="球団A"><span>投手A</span></div><div class="team_right"><img alt="球団B"><span>投手B</span></div><div class="info">球場 14:00</div></div></div></div>',2026);assert.equal(data.date,'2026-10-11');assert.equal(data.games[0].pitchers[1].name,'投手B');assert.throws(()=>parseStarters('<html></html>',2026));
});
test('club scoreboard preserves finished zero scores and suppresses scheduled placeholder zeros',()=>{
 const event=(id,complete)=>({id,date:'2026-10-10T16:00:00Z',competitions:[{status:{type:{state:complete?'post':'pre',completed:complete}},competitors:[{homeAway:'home',team:{displayName:'Club A'},score:'0'},{homeAway:'away',team:{displayName:'Club B'},score:'0'}]}]});const rows=parseClubBoard({events:[event('123',true),event('124',false),event('bad',true)]});assert.equal(rows.length,2);assert.equal(rows[0].date,'2026-10-11');assert.equal(rows[0].home.score,0);assert.equal(rows[1].home.score,null);assert.match(rows[0].url,/gameId\/123$/);
});
test('FIFA archive preserves official releases across years, updates same date and keeps history on failure',()=>{
 const snapshot=(date,rank)=>({fifa:{ok:true,data:{date,rows:[{code:'JPN',rank,points:1600}]}}});let fifaHistory=captureFifaHistory(null,snapshot('2026-09-01',20));fifaHistory=captureFifaHistory({fifaHistory},snapshot('2026-10-01',19));fifaHistory=captureFifaHistory({fifaHistory},snapshot('2026-10-01',18));assert.equal(fifaHistory.length,2);assert.equal(fifaHistory[1].rows[0].rank,18);assert.equal(captureFifaHistory({fifaHistory},{fifa:{ok:false}}).length,2);fifaHistory=captureFifaHistory({fifaHistory},snapshot('2027-01-01',17));assert.equal(fifaHistory.length,3);
});
test('weekly overseas collection uses bounded month queries across New Year and filters matches by Tokyo dates',async()=>{
 const {collectEnhancements}=await import('../lib/enhancements.mjs');const calls=[];
 const squad='<div class="section-block"><h4>MF/FW</h4><div class="competition-member">'+Array.from({length:11},(_,i)=>`<a href="/samuraiblue/member/p_${i}.html"><span class="name">選手${i}</span><span class="status">リーズ・ユナイテッド／イングランド</span></a>`).join('')+'</div></div>';
 const event=(id,date)=>({id,date,competitions:[{status:{type:{state:'pre'}},competitors:[{homeAway:'home',team:{displayName:'Leeds United'},score:'0'},{homeAway:'away',team:{displayName:'Other'},score:'0'}]}]});
 const getText=async url=>{calls.push(url);if(url.includes('/scoreboard?'))return JSON.stringify({events:[event('1','2026-12-31T16:00:00Z'),event('2','2027-01-10T16:00:00Z')]});if(url.includes('samuraiblue_2026/member/'))return '<table><tr><td>12/28</td><td><a href="/samuraiblue/cup/member.html">招集メンバー</a></td></tr></table>';if(url.includes('cup/member.html'))return squad;if(url.includes('announcement/starter'))return '<div class="contents"><h4>12月31日の予告先発投手</h4></div>';throw Error('unavailable');};
 const result=await collectEnhancements(getText,{today:'2026-12-31',year:2026,footballGames:{ok:true,data:[]}});assert.equal(result.overseas.ok,true);assert.equal(result.overseas.data.from,'2026-12-28');assert.equal(result.overseas.data.to,'2027-01-03');assert.equal(result.overseas.data.players[0].games.length,1);assert.equal(result.overseas.data.players[0].games.every(g=>g.date==='2027-01-01'),true);assert.equal(calls.filter(url=>url.includes('/scoreboard?')).length,24);assert.ok(calls.some(url=>url.includes('dates=202701')));assert.ok(calls.every(url=>!url.includes('20261228-20270103')));
 const failed=await collectEnhancements(async url=>{if(url.includes('/scoreboard?'))throw Error('offline');return getText(url);},{today:'2026-12-31',year:2026,footballGames:{ok:true,data:[]}});assert.equal(failed.overseas.ok,false);
});
