import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';

const categories=[{id:'avg',label:'打率',unit:''},{id:'hr',label:'本塁打',unit:'本'},{id:'rbi',label:'打点',unit:'点'},{id:'w',label:'勝利',unit:'勝'},{id:'era',label:'防御率',unit:'',low:true},{id:'so',label:'奪三振',unit:'個'}];
const ok=data=>({ok:true,data,source:'https://npb.jp/',fetchedAt:'2026-12-31T16:00:00Z'});
const fixture=()=>({year:2027,today:'2027-01-01',generatedAt:'2026-12-31T16:00:00Z',categories,
 standings:ok({c:[{team:'阪神タイガース',wins:'80',losses:'60',draws:'3',pct:'.571',gap:'-'},{team:'読売ジャイアンツ',wins:'77',losses:'62',draws:'4',pct:'.554',gap:'2.5'}],p:[]}),
 baseballGames:ok([{date:'2026-12-28',home:'阪神',away:'巨人',status:'finished',time:'14:00',venue:'甲子園'},{date:'2027-01-01',home:'巨人',away:'DeNA',status:'scheduled',time:'14:00',venue:'東京ドーム'},{date:'2027-01-02',home:'阪神',away:'広島',status:'cancelled',time:'14:00',venue:'甲子園'},{date:'2027-01-04',home:'巨人',away:'阪神',status:'scheduled',time:'18:00',venue:'東京ドーム'}]),
 footballGames:ok([{date:'2027-01-03',opponent:'対戦国',status:'scheduled',url:'https://www.jfa.jp/',venue:'国立'}]),fifa:{ok:false},baseballNews:ok([]),footballNews:ok([]),
 leaders:Object.fromEntries(categories.map(c=>[c.id,{c:ok(c.id==='era'?[{name:'投手A',team:'神',league:'c',value:'1.80'},{name:'投手B',team:'巨',league:'c',value:'2.13'}]:[{name:'選手A',team:'神',league:'c',value:c.id==='avg'?'.320':'39'},{name:'選手B',team:'巨',league:'c',value:c.id==='avg'?'.297':'20'}]),p:ok([{name:'選手C',team:'西',league:'p',value:c.id==='era'?'1.60':c.id==='avg'?'.330':'45'}])}]))});
async function setup(options={}){
 const requests=[];const data=fixture();options.configure?.(data);const {window,document}=parseHTML(await readFile('public/index.html','utf8'));
 window.location={hash:''};window.history={pushState(_state,_title,url){window.location.hash=url;}};const storage=new Map(Object.entries(options.saved||{}));window.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k),key:i=>[...storage.keys()][i],get length(){return storage.size;}};
 Object.defineProperty(window.HTMLSelectElement.prototype,'options',{configurable:true,get(){return this.querySelectorAll('option');}});
 Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this._value??this.querySelector('option')?.getAttribute('value')??'';},set(v){this._value=v;}});
 class Clock extends Date{constructor(...args){super(...(args.length?args:['2026-12-31T16:00:00Z']));}static now(){return new Date('2026-12-31T16:00:00Z').getTime();}}
 const context=vm.createContext({window,document,Intl,URL,Date:Clock,Number,String,Set,Math,AbortSignal,setInterval(){},fetch:async(url,init)=>{requests.push({url,init});return {ok:true,json:async()=>data};},...options.globals});
 vm.runInContext(await readFile('public/app.js','utf8'),context);await new Promise(r=>setTimeout(r,0));
 return {data,context,document,window,storage,requests,$:id=>document.getElementById(id),change:(id,value)=>{const el=document.getElementById(id);el.value=value;el.dispatchEvent(new window.Event('change'));}};
}
test('home uses Tokyo today and Monday to Sunday across the year boundary',async()=>{
 const {$}=await setup();assert.equal($('today-count').textContent,'1試合');assert.match($('today-games').textContent,/巨人 × DeNA/);assert.equal($('week-count').textContent,'4試合');assert.match($('week-games').textContent,/終了/);assert.match($('week-games').textContent,/中止・延期/);assert.match($('week-games').textContent,/対戦国/);assert.match($('week-range').textContent,/12月28日/);assert.match($('week-range').textContent,/1月3日/);assert.doesNotMatch($('week-games').textContent,/巨人 × 阪神/);
});
test('calendar filters include the selected day and follow favorite changes',async()=>{
 const {document,$,change}=await setup();const filter=value=>document.querySelector(`[data-calendar-filter="${value}"]`).click();
 filter('football');assert.equal($('calendar').querySelectorAll('.calendar-event.baseball').length,0);assert.equal($('calendar').querySelectorAll('.calendar-event.football').length,1);assert.doesNotMatch($('day-games').textContent,/巨人/);
 filter('favorite');assert.equal($('calendar').querySelectorAll('.calendar-event').length,0);assert.match($('calendar-filter-note').textContent,/応援球団を選ぶ/);
 change('favorite-team','巨');assert.equal($('calendar').querySelectorAll('.calendar-event.football').length,0);assert.equal($('calendar').querySelectorAll('.calendar-event').length,2);assert.match($('day-games').textContent,/巨人/);
 change('favorite-team','神');assert.doesNotMatch($('day-games').textContent,/巨人/);filter('baseball');assert.equal($('calendar').querySelectorAll('.calendar-event').length,3);filter('all');assert.equal($('calendar').querySelectorAll('.calendar-event').length,4);
});
test('title gaps compare team players with league leaders and preserve decimal precision',async()=>{
 const {document,$,change}=await setup();assert.match($('leaders').textContent,/0.023/);change('leader-team','巨');assert.match($('leaders').textContent,/リーグ首位との差/);assert.match($('leaders').textContent,/0.023/);
 document.querySelector('[data-category="hr"]').click();assert.match($('leaders').textContent,/19 本/);document.querySelector('[data-category="era"]').click();assert.match($('leaders').textContent,/0.33/);
 document.querySelector('#leader-tabs [data-league="all"]').click();assert.match($('leaders').textContent,/0.20/);assert.match($('leaders').textContent,/首位（差なし）/);
});
test('failed sources and absent qualified players do not become fabricated summaries',async()=>{
 const {data,context,$,change}=await setup();change('favorite-team','巨');data.standings.ok=false;data.baseballGames.ok=false;data.leaders.avg.c.data=[];data.leaders.hr.c.ok=false;await vm.runInContext('refresh()',context);
 assert.match($('home-schedule-note').textContent,/取得成功分のみ/);assert.equal($('today-count').textContent,'0試合');assert.equal($('week-count').textContent,'1試合');
});
test('favorite players are marked without filtering other teams and reset immediately',async()=>{
 const {$,document,change}=await setup();change('favorite-team','巨');assert.equal($('leaders').querySelectorAll('tbody tr').length,2);assert.equal($('leaders').querySelectorAll('.favorite-player').length,1);assert.match($('leaders').querySelector('.favorite-player').textContent,/選手B/);assert.match($('leaders').querySelector('.favorite-player-mark').getAttribute('aria-label'),/応援球団/);$('settings-reset').click();assert.equal($('leaders').querySelectorAll('.favorite-player').length,0);assert.ok(document.querySelector('.stat-help summary'));assert.match(document.querySelector('.stat-help').textContent,/引き分け/);
});
test('previous comparison ranks all players, handles corrections and missing baselines',async()=>{
 const {data,context,$,document}=await setup();
 data.previous=JSON.parse(JSON.stringify({year:data.year,generatedAt:'2026-12-31T15:00:00Z',standings:data.standings,leaders:data.leaders}));
 data.previous.standings.data.c.reverse();data.previous.standings.data.c[1].wins='79';
 data.previous.leaders.hr.c.data=[{name:'選手A',team:'神',league:'c',value:'38'},...Array.from({length:11},(_,i)=>({name:'別選手'+i,team:'神',league:'c',value:String(37-i)})),{name:'選手B',team:'巨',league:'c',value:'19'}];
 await vm.runInContext('refresh()',context);assert.match($('standings').textContent,/↑ 1位上昇/);assert.match($('standings').textContent,/勝 \+1/);assert.match($('comparison-time').textContent,/前回比の基準/);
 document.querySelector('[data-category="hr"]').click();assert.match($('leaders').textContent,/↑ 11位上昇/);assert.match($('leaders').textContent,/\+1 本/);
 data.leaders.hr.c.data[0].value='37';await vm.runInContext('refresh()',context);assert.match($('leaders').textContent,/-1 本/);
 data.previous.leaders.hr.c.ok=false;await vm.runInContext('refresh()',context);assert.match($('leaders').textContent,/比較なし/);
 data.previous.year=2026;await vm.runInContext('refresh()',context);assert.match($('comparison-time').textContent,/比較できる前回/);assert.match($('standings').textContent,/比較なし/);
});
test('next fixture simulation updates both opponents and handles unknown matches safely',async()=>{
 const {data,context,$,change}=await setup();data.fifa={ok:true,data:{date:'2026-12-01',rows:[{rank:1,code:'ESP',name:'Spain',points:1700},{rank:2,code:'BRA',name:'Brazil',points:1608},{rank:3,code:'JPN',name:'Japan',points:1600},{rank:4,code:'ARG',name:'Argentina',points:1599}]}};
 data.footballGames.data=[{date:'2027-01-04',opponent:'アルゼンチン',competition:'予選',status:'scheduled'},{date:'2027-01-02',opponent:'ブラジル',competition:'予選',status:'finished'},{date:'2027-01-03',opponent:'ブラジル',competition:'FIFAワールドカップ予選',status:'scheduled'}];
 await vm.runInContext('refresh()',context);assert.equal($('simulator').hidden,false);assert.match($('roadmap').textContent,/日本 × ブラジル/);assert.match($('roadmap').textContent,/1月3日/);assert.match($('opponent').textContent,/ブラジル/);assert.equal($('importance').value,'25');
 change('importance','10');const scenarios=$('simulation').querySelectorAll('.sim-result');assert.match(scenarios[0].textContent,/概算 2位/);assert.match(scenarios[2].textContent,/概算 4位/);assert.match(scenarios[0].textContent,/想定ポイントを超過/);
 data.footballGames.data[2].competition='大会種別未確定';await vm.runInContext('refresh()',context);assert.equal($('importance').value,'');assert.match($('simulation').textContent,/試合の種類を選ぶ/);
 data.footballGames.data[2].opponent='未定';await vm.runInContext('refresh()',context);assert.equal($('simulator').hidden,true);assert.match($('roadmap').textContent,/照合できない/);
 data.footballGames.ok=false;await vm.runInContext('refresh()',context);assert.match($('roadmap').textContent,/日程を取得できない/);
});
test('match weighting distinguishes confirmed windows, stages and unknown competitions',async()=>{
 const {context}=await setup();const importance=(competition,date='2026-11-14')=>vm.runInContext(`matchImportance(${JSON.stringify({competition,date})})`,context);
 assert.equal(importance('MIZUHO BLUE CHALLENGE'),'10');assert.equal(importance('国際親善試合','2026-11-18'),'5');assert.equal(importance('国際親善試合','2027-03-20'),'');assert.equal(importance('FIFAワールドカップ予選'),'25');assert.equal(importance('AFCアジアカップ グループステージ'),'35');assert.equal(importance('AFCアジアカップ 準々決勝'),'40');assert.equal(importance('FIFAワールドカップ 準々決勝'),'60');assert.equal(importance('FIFAワールドカップ'),'');assert.equal(importance('大会未定'),'');
});
test('region persists with theme and favorite, while old font settings are ignored',async()=>{
 const settings='sports-desk-preferences-v1';const ui=await setup({saved:{[settings]:JSON.stringify({theme:'green',favorite:'巨',fontSize:'large'})}});assert.equal(ui.document.documentElement.dataset.fontSize,undefined);assert.equal(ui.$('font-size-options'),null);ui.change('home-region','27');assert.equal(ui.$('settings-region').value,'27');const value=JSON.parse(ui.storage.get(settings));assert.equal(value.theme,'green');assert.equal(value.favorite,'巨');assert.equal(value.region,'27');assert.equal(value.fontSize,undefined);const loaded=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(loaded.$('home-region').value,'27');loaded.$('settings-reset').click();assert.equal(loaded.$('home-region').value,'13');
});
test('recent results use favorite perspective, preserve zero scores and omit cancelled or future games',async()=>{
 const ui=await setup({configure:d=>{d.baseballResults=ok([{date:'2027-01-01',home:'巨人',away:'阪神',homeScore:0,awayScore:0,status:'finished'},...Array.from({length:5},(_,i)=>({date:`2026-12-${31-i}`,home:'阪神',away:'巨人',homeScore:3,awayScore:1,status:'finished'})),{date:'2027-01-03',home:'巨人',away:'阪神',homeScore:5,awayScore:0,status:'finished'},{date:'2027-01-01',home:'巨人',away:'阪神',status:'cancelled'}]);}});ui.change('favorite-team','巨');assert.equal(ui.$('baseball-results').querySelectorAll('.recent-result').length,5);assert.match(ui.$('baseball-results').textContent,/0 − 0/);assert.match(ui.$('baseball-results').textContent,/引き分け/);assert.match(ui.$('baseball-results').textContent,/負け/);assert.doesNotMatch(ui.$('baseball-results').textContent,/5 − 0/);
 ui.data.baseballResults.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('baseball-results').textContent,/取得できません/);
});
test('opponent profile shows official point gap and latest known head-to-head; PK score remains separate',async()=>{
 const ui=await setup({configure:d=>{
  d.fifa={ok:true,data:{date:'2026-12-01',rows:[{rank:1,code:'BRA',name:'Brazil',points:1700},{rank:2,code:'JPN',name:'Japan',points:1600}]}};
  d.footballGames=ok([{date:'2027-01-03',opponent:'ブラジル',status:'scheduled',competition:'親善試合'}]);d.footballHistory=ok([{date:'2026-12-30',opponent:'エクアドル',status:'finished',japanScore:0,opponentScore:0,score:'〇0-0 PK5-4',result:'win'},{date:'2026-12-20',opponent:'ブラジル',status:'finished',japanScore:1,opponentScore:2,score:'●1-2',result:'loss'},{date:'2027-01-04',opponent:'ブラジル',status:'finished',japanScore:9,opponentScore:0}]);
 }});assert.match(ui.$('football-result').textContent,/勝ち（PK戦）/);assert.match(ui.$('football-result').textContent,/0 − 0/);assert.match(ui.$('football-result').textContent,/PK5-4/);assert.match(ui.$('opponent-profile').textContent,/1位/);assert.match(ui.$('opponent-profile').textContent,/日本より 100.00 pts 上/);assert.match(ui.$('opponent-profile').textContent,/1 − 2/);assert.doesNotMatch(ui.$('opponent-profile').textContent,/9 − 0/);
 ui.data.footballHistory.data=[];await vm.runInContext('refresh()',ui.context);assert.match(ui.$('opponent-profile').textContent,/見つかりません/);ui.data.footballHistory.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('football-result').textContent,/取得できません/);
});

test('settings region changes the home without affecting favorite and survives reload',async()=>{
 const ui=await setup();ui.change('favorite-team','巨');ui.change('settings-region','01');assert.equal(ui.$('home-region').value,'01');const restored=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('home-region').value,'01');assert.equal(restored.$('favorite-team').value,'巨');
});
test('news shows only three newest entries and calendar counts follow its filter',async()=>{
 const ui=await setup({configure:d=>{for(const sport of ['baseball','football'])d[sport+'News']=ok(Array.from({length:6},(_,i)=>({date:'2027-01-01',title:'News '+i,url:'https://npb.jp/'+i})));}});for(const sport of ['baseball','football'])assert.equal(ui.$(sport+'-news').querySelectorAll('a').length,3);const cell=ui.$('calendar').querySelector('[data-day="2027-01-01"]');assert.equal(cell.querySelector('.day-count.baseball').textContent,'⚾1');cell.click();assert.match(ui.$('day-games').textContent,/巨人/);assert.equal(ui.document.querySelector('.week-summary').hasAttribute('open'),false);assert.equal(ui.document.querySelector('#home .favorite-card'),null);
});

function draftFixture(d){
 d.draft={seasonComplete:false,clubs:{}};for(const [team,prefix] of [['神','A'],['巨','B']]){const players=Array.from({length:5},(_,i)=>({team,name:prefix+(i+1),values:{avg:prefix==='A'?'.300':'.280',hr:String(i),h:'100',rbi:'50',w:'10',era:prefix==='A'?'2.00':'3.00',sv:'0'}}));d.draft.clubs[team]={bat:ok(players),pit:ok(players)};}
 d.leaders.avg.c=ok(Object.values(d.draft.clubs).flatMap(c=>c.bat.data.map(p=>({...p,league:'c',value:p.values.avg}))));d.leaders.era.c=ok(Object.values(d.draft.clubs).flatMap(c=>c.pit.data.map(p=>({...p,league:'c',value:p.values.era}))));
}
async function fillDraft(ui,id='hr'){
 ui.document.querySelector(`#draft-categories [data-draft-category="${id}"]`).click();
 for(let army=0;army<2;army++)for(let round=0;round<5;round++)for(const [field,value] of [['team',army===0?'神':'巨'],['name',(army===0?'A':'B')+(round+1)]]){const el=ui.document.querySelector(`[data-draft-field="${field}"][data-army="${army}"][data-round="${round}"]`);el.value=value;el.dispatchEvent(new ui.window.Event('change',{bubbles:true}));}
}
test('draft has seven five-round departments, sums real zeros and persists names and picks',async()=>{
 const ui=await setup({configure:draftFixture});assert.equal(ui.$('draft-categories').querySelectorAll('button').length,7);assert.equal(ui.$('draft-picks').querySelectorAll('.draft-round').length,10);await fillDraft(ui);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),10);assert.match(ui.$('draft-picks').textContent,/現在の成績0本/);ui.change('draft-name-a','りり軍');const restored=await setup({configure:draftFixture,saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('draft-name-a').value,'りり軍');assert.match(restored.$('draft-overview').textContent,/引き分け/);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).ready',restored.context),true);
});
test('draft uses qualifying rate averages, ERA favors lower and missing data never becomes zero',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.year=2026;}});await fillDraft(ui,'avg');assert.equal(vm.runInContext('draftTotal(draftCategories[0],0).value',ui.context),.3);assert.match(ui.$('draft-overview').textContent,/A軍 優勢/);ui.data.leaders.avg.c.data=ui.data.leaders.avg.c.data.filter(p=>p.name!=='A1');await vm.runInContext('refresh()',ui.context);assert.match(ui.$('draft-picks').textContent,/規定未達/);assert.equal(vm.runInContext('draftTotal(draftCategories[0],0).count',ui.context),4);await fillDraft(ui,'era');assert.equal(vm.runInContext('draftDecision(draftCategories[5],draftTotal(draftCategories[5],0),draftTotal(draftCategories[5],1))',ui.context),0);ui.data.draft.clubs['神'].pit.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('draft-picks').textContent,/取得失敗/);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).value',ui.context),null);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).ready',ui.context),false);
});
test('draft blocks duplicate picks, updates fetched stats and starts a separate season',async()=>{
 const ui=await setup({configure:draftFixture});await fillDraft(ui);const duplicate=ui.document.querySelector('[data-draft-field="name"][data-army="0"][data-round="1"]');duplicate.value='A1';duplicate.dispatchEvent(new ui.window.Event('change',{bubbles:true}));assert.match(ui.$('draft-save-status').textContent,/指名済み/);assert.equal(vm.runInContext('draftState.picks.hr[0][1].name',ui.context),'A2');ui.data.draft.clubs['神'].bat.data[0].values.hr='12';await vm.runInContext('refresh()',ui.context);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),22);ui.data.year=2028;await vm.runInContext('refresh()',ui.context);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).selected',ui.context),0);assert.ok(ui.storage.has('sports-desk-draft-v1-2027'));
});
test('draft only declares final comparison when all departments are ready and handles blocked storage',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.year=2026;}});ui.data.draft.seasonComplete=true;for(const id of ['avg','hr','h','rbi','w','era','sv'])await fillDraft(ui,id);await vm.runInContext('refresh()',ui.context);assert.match(ui.$('draft-score').textContent,/最終比較/);assert.match(ui.$('draft-score').textContent,/A軍 2勝/);assert.match(ui.$('draft-score').textContent,/引分 5/);ui.window.localStorage.setItem=()=>{throw Error('blocked');};ui.change('draft-name-a','<img src=x>');assert.match(ui.$('draft-save-status').textContent,/保存できません/);assert.equal(ui.$('draft-overview').querySelector('img'),null);assert.match(ui.$('draft-overview').textContent,/<img src=x>/);
});

test('menu collapses and reopens, persists independently, and update time lives in header',async()=>{
 const ui=await setup();assert.equal(ui.$('data-updated').closest('header').classList.contains('topbar'),true);assert.match(ui.$('data-updated').textContent,/データ取得・集計完了/);assert.equal(ui.$('favorite-summary'),null);assert.equal(ui.$('site-menu').hidden,false);ui.$('menu-toggle').click();assert.equal(ui.$('site-menu').hidden,true);assert.equal(ui.$('menu-toggle').getAttribute('aria-expanded'),'false');assert.match(ui.$('menu-toggle').getAttribute('aria-label'),/開く/);const restored=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('site-menu').hidden,true);restored.$('menu-toggle').click();assert.equal(restored.$('site-menu').hidden,false);assert.equal(restored.$('menu-toggle').getAttribute('aria-expanded'),'true');restored.window.localStorage.setItem=()=>{throw Error('blocked');};restored.$('menu-toggle').click();assert.equal(restored.$('site-menu').hidden,true);
});

function searchDraft(ui,query,army=0,round=0){const input=ui.document.querySelector(`[data-draft-search][data-army="${army}"][data-round="${round}"]`);input.value=query;input.dispatchEvent(new ui.window.Event('input',{bubbles:true}));return ui.$(`draft-player-${army}-${round}`);}
async function previewBackup(ui,text,size=new Blob([text]).size){Object.defineProperty(ui.$('backup-file'),'files',{configurable:true,value:[{name:'backup.json',size,text:async()=>text}]});ui.$('backup-file').dispatchEvent(new ui.window.Event('change'));await new Promise(r=>setTimeout(r,0));}
test('draft search filters live, normalizes full-width names and preserves a selected player with no matches',async()=>{
 const ui=await setup({configure:draftFixture});await fillDraft(ui);assert.equal(searchDraft(ui,'Ａ ２').querySelectorAll('option').length,3);assert.match(ui.$('draft-player-0-0').textContent,/A2/);assert.equal(ui.$('draft-player-0-0').value,'A1');assert.match(ui.$('draft-player-0-0').querySelector('[value="A2"]').getAttribute('disabled'),/^$/);searchDraft(ui,'存在しない名前');assert.equal(ui.$('draft-player-0-0').value,'A1');assert.match(ui.$('draft-picks').querySelector('[data-search-count="0-0"]').textContent,/0人/);assert.equal(vm.runInContext('draftState.picks.hr[0][0].name',ui.context),'A1');const team=ui.document.querySelector('[data-draft-field="team"][data-army="0"][data-round="0"]');team.value='巨';team.dispatchEvent(new ui.window.Event('change',{bubbles:true}));assert.equal(ui.document.querySelector('[data-draft-search][data-army="0"][data-round="0"]').value,'');assert.equal(ui.$('draft-player-0-0').value,'');
});
test('JSON export downloads all saved seasons with preferences but no official statistics or unrelated keys',async()=>{
 const blobs=new Map(),downloads=[];let revoked=false;const ui=await setup({configure:draftFixture,globals:{Blob,URL:{createObjectURL(blob){blobs.set('blob:backup',blob);return 'blob:backup';},revokeObjectURL(){revoked=true;}},setTimeout(callback){callback();}}});await fillDraft(ui);ui.change('draft-name-a','移行する軍');ui.change('favorite-team','巨');ui.change('home-region','27');ui.$('menu-toggle').click();const old=vm.runInContext('JSON.stringify(draftState)',ui.context);ui.storage.set('sports-desk-draft-v1-2026',old);ui.storage.set('unrelated-secret','must-not-export');ui.document.createElement=(original=>function(tag){const el=original.call(this,tag);if(tag==='a')el.click=()=>downloads.push({href:el.href,filename:el.download});return el;})(ui.document.createElement);ui.$('backup-export').click();assert.equal(downloads.length,1);assert.match(downloads[0].filename,/sports-desk-backup-.*\.json/);const exported=JSON.parse(await blobs.get('blob:backup').text());assert.equal(exported.preferences.favorite,'巨');assert.equal(exported.preferences.region,'27');assert.equal(exported.preferences.fontSize,undefined);assert.equal(exported.menuCollapsed,true);assert.equal(Object.keys(exported.drafts).length,2);assert.equal(exported.drafts['2027'].names[0],'移行する軍');assert.doesNotMatch(JSON.stringify(exported),/must-not-export|generatedAt|leaders/);assert.equal(revoked,true);
});
test('JSON import previews before mutation, restores another browser and preserves years absent from file',async()=>{
 const source=await setup({configure:draftFixture});await fillDraft(source);source.change('draft-name-a','引継ぎ軍');source.change('favorite-team','神');source.$('menu-toggle').click();const text=vm.runInContext('JSON.stringify(collectBackup())',source.context);const target=await setup({configure:draftFixture});target.storage.set('sports-desk-draft-v1-2025',vm.runInContext('JSON.stringify(emptyDraft())',target.context));await previewBackup(target,text);assert.equal(target.$('backup-preview').hidden,false);assert.match(target.$('backup-preview-text').textContent,/引継ぎ軍/);assert.equal(target.$('favorite-team').value,'all');target.$('backup-apply').click();assert.equal(target.$('favorite-team').value,'神');assert.equal(target.$('site-menu').hidden,true);assert.equal(target.$('draft-name-a').value,'引継ぎ軍');assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',target.context),10);assert.ok(target.storage.has('sports-desk-draft-v1-2025'));assert.equal(target.$('backup-preview').hidden,true);const reloaded=await setup({configure:draftFixture,saved:Object.fromEntries(target.storage)});assert.equal(reloaded.$('draft-name-a').value,'引継ぎ軍');assert.equal(reloaded.$('favorite-team').value,'神');
});
test('JSON validation rejects malformed, oversized, unsupported, duplicate and prototype-key data without writes',async()=>{
 const ui=await setup({configure:draftFixture});const good=JSON.parse(vm.runInContext('JSON.stringify(collectBackup())',ui.context));const before=JSON.stringify([...ui.storage]);for(const bad of ['{broken',JSON.stringify({...good,version:99}),JSON.stringify({...good,preferences:{...good.preferences,theme:'unknown'}}),JSON.stringify({...good,drafts:{'../../x':good.drafts['2027']}}),JSON.stringify(good).replace('"drafts":{','"drafts":{"__proto__":{},')]){await previewBackup(ui,bad);assert.equal(ui.$('backup-preview').hidden,true);assert.match(ui.$('backup-status').textContent,/読み込めません/);assert.equal(JSON.stringify([...ui.storage]),before);}await previewBackup(ui,JSON.stringify(good),1024*1024+1);assert.match(ui.$('backup-status').textContent,/1MB/);const duplicate=structuredClone(good);duplicate.drafts['2027'].picks.hr[0][0]={team:'神',name:'A1'};duplicate.drafts['2027'].picks.hr[1][0]={team:'神',name:'A1'};await previewBackup(ui,JSON.stringify(duplicate));assert.match(ui.$('backup-status').textContent,/重複指名/);assert.equal(JSON.stringify([...ui.storage]),before);
});
test('JSON cancel and storage failure keep existing selections and preferences',async()=>{
 const source=await setup({configure:draftFixture});await fillDraft(source);source.change('favorite-team','巨');const text=vm.runInContext('JSON.stringify(collectBackup())',source.context);const ui=await setup({configure:draftFixture});ui.change('favorite-team','神');const before=JSON.stringify([...ui.storage]);await previewBackup(ui,text);ui.$('backup-cancel').click();ui.$('backup-apply').click();assert.equal(ui.$('favorite-team').value,'神');assert.equal(JSON.stringify([...ui.storage]),before);await previewBackup(ui,text);const original=ui.window.localStorage.setItem;let writes=0;ui.window.localStorage.setItem=(key,value)=>{if(++writes===3)throw Error('quota');return original(key,value);};ui.$('backup-apply').click();assert.match(ui.$('backup-status').textContent,/保存できません/);assert.equal(JSON.stringify([...ui.storage]),before);assert.equal(ui.$('favorite-team').value,'神');assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).selected',ui.context),0);
});

function uiHistory(d,year=2027){const rows=Object.entries(d.draft.clubs).flatMap(([team,club])=>club.bat.data.map(p=>[team,p.name,p.values.avg,p.values.hr,p.values.h,p.values.rbi,p.values.w,p.values.era,p.values.sv,true,true]));const feb=rows.map(row=>row.map((value,i)=>i===3?String(Number(value)+2):value));return {version:1,seasons:{[year]:{latestMonth:year+'-02',months:{[year+'-01']:{generatedAt:year+'-01-31T10:00:00Z',rows,seasonComplete:false},[year+'-02']:{generatedAt:year+'-02-28T10:00:00Z',rows:feb,seasonComplete:true}}}}};}
test('monthly view shows cumulative totals, consecutive-month changes and explicitly unrecorded months',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.draftHistory=uiHistory(d);}});await fillDraft(ui);const rows=ui.$('draft-monthly').querySelectorAll('tbody tr');assert.equal(rows.length,12);assert.match(rows[0].textContent,/10/);assert.match(rows[1].textContent,/20/);assert.match(rows[1].textContent,/\+10 本/);assert.match(rows[2].textContent,/未記録/);delete ui.data.draftHistory.seasons['2027'].months['2027-01'];await vm.runInContext('refresh()',ui.context);assert.doesNotMatch(ui.$('draft-monthly').querySelectorAll('tbody tr')[1].textContent,/\+10 本/);
});
test('year selector separates saved picks, uses archived season stats and never substitutes future stats',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.draftHistory=uiHistory(d,2026);}});await fillDraft(ui);ui.change('draft-name-a','2027軍');ui.change('draft-year-select','2026');await fillDraft(ui);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),20);ui.change('draft-name-a','2026軍');ui.change('draft-year-select','2028');await fillDraft(ui);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),null);assert.match(ui.$('draft-picks').textContent,/年度成績未公開/);ui.change('draft-year-select','2027');assert.equal(ui.$('draft-name-a').value,'2027軍');assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),10);ui.change('draft-year-select','2026');assert.equal(ui.$('draft-name-a').value,'2026軍');assert.ok(ui.storage.has('sports-desk-draft-v1-2028'));ui.change('draft-year-select','2028');ui.data.year=2028;await vm.runInContext('refresh()',ui.context);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),10);
});
test('2026 ERA special Imai pick is unmeasurable, excluded from average, portable, and forbidden in other categories or years',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.year=2026;}});await fillDraft(ui,'era');for(const [field,value] of [['team','MLB'],['name','今井 達也']]){const el=ui.document.querySelector(`[data-draft-field="${field}"][data-army="0"][data-round="0"]`);el.value=value;el.dispatchEvent(new ui.window.Event('change',{bubbles:true}));}assert.match(ui.$('draft-picks').textContent,/計測不可/);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).count',ui.context),4);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).value',ui.context),2);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).ready',ui.context),true);const backup=vm.runInContext('JSON.stringify(validateBackup(collectBackup()))',ui.context);const loaded=await setup({configure:d=>{draftFixture(d);d.year=2026;},saved:Object.fromEntries(ui.storage)});assert.equal(vm.runInContext('draftState.picks.era[0][0].name',loaded.context),'今井 達也');const parsed=JSON.parse(backup);parsed.drafts['2027']=parsed.drafts['2026'];delete parsed.drafts['2026'];ui.context.badBackup=JSON.stringify(parsed);assert.throws(()=>vm.runInContext('validateBackup(JSON.parse(badBackup))',ui.context));ui.document.querySelector('#draft-categories [data-draft-category="hr"]').click();assert.equal(ui.document.querySelector('[data-draft-field="team"] [value="MLB"]'),null);
});

test('freshness warning remains for stale data and refresh bypasses cache including tab resume',async()=>{
 const ui=await setup({configure:d=>{d.fifa=ok({date:'2026-12-31',rows:[{code:'JPN',name:'Japan',rank:2,points:1600},{code:'ESP',name:'Spain',rank:1,points:1800}]});d.generatedAt='2026-12-31T12:00:00Z';}});assert.match(ui.$('status').textContent,/2時間以上/);assert.equal(ui.$('status').classList.contains('error'),true);assert.match(ui.requests[0].url,/sports\.json\?t=\d+/);assert.equal(ui.requests[0].init.cache,'no-store');ui.data.generatedAt='2026-12-31T16:00:00Z';const before=ui.requests.length;ui.document.dispatchEvent(new ui.window.Event('visibilitychange'));await new Promise(r=>setTimeout(r,0));assert.equal(ui.requests.length,before+1);assert.doesNotMatch(ui.$('status').textContent,/2時間以上/);assert.equal(ui.$('status').classList.contains('error'),false);
});

test('daily home switches selected region, limits both news lists to three, escapes headlines and distinguishes unavailable data',async()=>{
 const region=(label)=>({weather:ok({area:label,station:label,issuedAt:'2027-01-01T00:00:00+09:00',days:[{date:'2027-01-01',weather:'晴れ',low:0,high:null,rain:0},{date:'2026-12-30',weather:'古い予報',low:2,high:4,rain:80}]}),news:ok({coverage:label,items:Array.from({length:5},(_,i)=>({title:label+'<script>悪意</script>'+i,date:'2027-01-01',url:'https://news.yahoo.co.jp/articles/'+i}))})});const ui=await setup({configure:d=>{d.daily={nationalNews:ok(Array.from({length:5},(_,i)=>({title:'全国'+i,date:'2027-01-01',url:'https://news.yahoo.co.jp/articles/n'+i}))),locations:{'13':region('東京地方'),'27':region('大阪府')}};}});assert.equal(ui.$('home-region').querySelectorAll('option').length,47);assert.equal(ui.$('national-news').querySelectorAll('a').length,3);assert.equal(ui.$('local-news').querySelectorAll('a').length,3);assert.equal(ui.$('local-news').querySelector('script'),null);assert.match(ui.$('home-weather').textContent,/0°/);assert.match(ui.$('home-weather').textContent,/0%/);assert.doesNotMatch(ui.$('home-weather').textContent,/古い予報/);ui.change('home-region','27');assert.match(ui.$('weather-heading').textContent,/大阪府/);assert.match(ui.$('local-news').textContent,/大阪府/);ui.data.daily.locations['27'].weather.ok=false;ui.data.daily.locations['27'].news.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('home-weather').textContent,/取得できません/);assert.match(ui.$('local-news').textContent,/取得できません/);assert.equal(ui.$('national-news').querySelectorAll('a').length,3);
});
test('rival display uses current opponent ranks and country perspective including PK, missing fixtures and partial failure',async()=>{
 const ui=await setup({configure:d=>{d.fifa=ok({date:'2026-12-31',rows:[{code:'ESP',rank:1,name:'Spain',points:1800},{code:'BRA',rank:2,name:'Brazil',points:1700},{code:'JPN',rank:3,name:'Japan',points:1600}]});const game={date:'2026-12-31',kickoff:'2026-12-31T10:00Z',timeKnown:true,home:{code:'BRA',name:'Brazil'},away:{code:'ESP',name:'Spain'},homeScore:0,awayScore:0,homePenalty:4,awayPenalty:5,status:'finished',url:'https://www.espn.com/',competition:'親善試合'};d.footballRivals=ok({countries:[{code:'ESP',games:ok([game,{...game,id:'next',date:'2027-01-02',kickoff:'2027-01-02T10:00Z',status:'scheduled',homePenalty:null,awayPenalty:null}])},{code:'BRA',games:{ok:false,source:'https://www.espn.com/'}}]});}});assert.equal(ui.$('football-rivals').querySelectorAll('details').length,2);const esp=ui.$('football-rivals').querySelector('[data-rival="ESP"]');assert.match(esp.textContent,/対 ブラジル/);assert.match(esp.textContent,/最新 2位/);assert.match(esp.textContent,/PK 5 − 4/);assert.match(esp.textContent,/予定/);assert.match(ui.$('football-rivals').querySelector('[data-rival="BRA"]').textContent,/取得できません/);ui.data.fifa.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('football-rivals').textContent,/特定できません/);
});
test('legacy JSON imports ignore retired font settings and preserve draft names while new region is validated',async()=>{
 const ui=await setup({configure:draftFixture});const backup=JSON.parse(vm.runInContext('JSON.stringify(collectBackup())',ui.context));delete backup.preferences.region;backup.preferences.fontSize='large';await previewBackup(ui,JSON.stringify(backup));assert.equal(ui.$('backup-preview').hidden,false);ui.$('backup-apply').click();assert.equal(ui.$('home-region').value,'13');assert.equal(ui.document.documentElement.dataset.fontSize,undefined);backup.preferences.region='99';await previewBackup(ui,JSON.stringify(backup));assert.match(ui.$('backup-status').textContent,/読み込めません/);
});

function pickDraftPlayer(ui,category,army,round,team,player){ui.document.querySelector(`#draft-categories [data-draft-category="${category}"]`).click();for(const [field,value] of [['team',team],['name',player]]){const el=ui.document.querySelector(`[data-draft-field="${field}"][data-army="${army}"][data-round="${round}"]`);el.value=value;el.dispatchEvent(new ui.window.Event('change',{bubbles:true}));}}
test('from 2027 duplicate picks are blocked across all categories, both armies and batting/pitching, then released on clearing',async()=>{
 const ui=await setup({configure:draftFixture});pickDraftPlayer(ui,'hr',0,0,'神','A1');pickDraftPlayer(ui,'avg',1,0,'神','A1');assert.equal(vm.runInContext('draftState.picks.avg[1][0].name',ui.context),'');assert.match(ui.$('draft-save-status').textContent,/全部門・両軍/);assert.equal(ui.$('draft-player-1-0').querySelector('[value="A1"]').hasAttribute('disabled'),true);pickDraftPlayer(ui,'w',0,0,'神','A1');assert.equal(vm.runInContext('draftState.picks.w[0][0].name',ui.context),'');pickDraftPlayer(ui,'avg',1,0,'神','A2');assert.equal(vm.runInContext('draftState.picks.avg[1][0].name',ui.context),'A2');pickDraftPlayer(ui,'hr',0,0,'神','');pickDraftPlayer(ui,'w',0,0,'神','A1');assert.equal(vm.runInContext('draftState.picks.w[0][0].name',ui.context),'A1');ui.change('draft-year-select','2028');pickDraftPlayer(ui,'hr',0,0,'神','A1');assert.equal(vm.runInContext('draftState.picks.hr[0][0].name',ui.context),'A1');
});
test('2026 keeps cross-category picks while same-category duplicates remain blocked',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.year=2026;}});pickDraftPlayer(ui,'hr',0,0,'神','A1');pickDraftPlayer(ui,'avg',1,0,'神','A1');assert.equal(vm.runInContext('draftState.picks.avg[1][0].name',ui.context),'A1');pickDraftPlayer(ui,'hr',1,0,'神','A1');assert.equal(vm.runInContext('draftState.picks.hr[1][0].name',ui.context),'');assert.match(ui.$('draft-duplicate-rule').textContent,/別部門では指名できます/);
});
test('JSON enforces the season rule including normalized names; 2026 and different years remain independent',async()=>{
 const ui=await setup({configure:draftFixture}),backup=JSON.parse(vm.runInContext('JSON.stringify(collectBackup())',ui.context));const draft=backup.drafts['2027'];draft.picks.hr[0][0]={team:'神',name:'Ａ １'};draft.picks.era[1][0]={team:'巨',name:'A1'};await previewBackup(ui,JSON.stringify(backup));assert.equal(ui.$('backup-preview').hidden,true);assert.match(ui.$('backup-status').textContent,/両軍・全部門/);backup.drafts={'2026':draft};await previewBackup(ui,JSON.stringify(backup));assert.equal(ui.$('backup-preview').hidden,false);draft.picks.era[1][0]=null;backup.drafts={'2027':draft,'2028':structuredClone(draft)};await previewBackup(ui,JSON.stringify(backup));assert.equal(ui.$('backup-preview').hidden,false);
});
test('existing cross-category duplicates are preserved, flagged and excluded from scoring until resolved, and can be backed up',async()=>{
 const original=await setup({configure:draftFixture});const state=JSON.parse(vm.runInContext('JSON.stringify(emptyDraft())',original.context));state.picks.hr[0][0]={team:'神',name:'A1'};state.picks.avg[1][0]={team:'神',name:'A1'};const raw=JSON.stringify(state),key='sports-desk-draft-v1-2027';const ui=await setup({configure:draftFixture,saved:{[key]:raw}});assert.equal(ui.storage.get(key),raw);assert.equal(ui.$('draft-duplicate-warning').hidden,false);assert.match(ui.$('draft-duplicate-warning').textContent,/A1/);assert.equal(vm.runInContext('draftState.picks.hr[0][0].name',ui.context),'A1');assert.equal(vm.runInContext('draftValue(draftCategories[1],draftState.picks.hr[0][0]).status',ui.context),'重複指名');const backup=JSON.parse(vm.runInContext('JSON.stringify(collectBackup())',ui.context));assert.equal(backup.drafts['2027'].picks.avg[1][0].name,'A1');ui.context.backupText=JSON.stringify(backup);assert.throws(()=>vm.runInContext('validateBackup(JSON.parse(backupText))',ui.context));pickDraftPlayer(ui,'avg',1,0,'神','A2');assert.equal(ui.$('draft-duplicate-warning').hidden,true);assert.equal(vm.runInContext('draftValue(draftCategories[1],draftState.picks.hr[0][0]).status',ui.context),'ok');assert.doesNotThrow(()=>vm.runInContext('validateBackup(collectBackup())',ui.context));
});
test('compact home and draft disclosures keep summaries visible, switch news and preserve the open editor after changes',async()=>{
 const ui=await setup({configure:draftFixture});assert.equal(ui.$('national-news-section').hidden,false);assert.equal(ui.$('local-news-section').hidden,true);ui.document.querySelector('[data-news-view="local"]').click();assert.equal(ui.$('national-news-section').hidden,true);assert.equal(ui.$('local-news-section').hidden,false);assert.equal(ui.document.querySelector('[data-news-view="local"]').getAttribute('aria-pressed'),'true');assert.equal(ui.$('draft-monthly').closest('details').hasAttribute('open'),false);assert.equal(ui.$('draft-picks').querySelectorAll('details[open]').length,0);let row=ui.$('draft-picks').querySelector('[data-draft-editor="1-2"]');row.setAttribute('open','');const field=row.querySelector('[data-draft-field="team"]');field.value='神';field.dispatchEvent(new ui.window.Event('change',{bubbles:true}));row=ui.$('draft-picks').querySelector('[data-draft-editor="1-2"]');assert.equal(row.hasAttribute('open'),true);const player=row.querySelector('[data-draft-field="name"]');player.value='A1';player.dispatchEvent(new ui.window.Event('change',{bubbles:true}));assert.match(ui.$('draft-picks').querySelector('[data-draft-editor="1-2"] summary').textContent,/A1/);assert.equal(ui.document.querySelector('#baseball-results').closest('.section-disclosure').hasAttribute('open'),false);
});

test('home visibility and ordering persist and are portable with backwards-compatible defaults',async()=>{
 const ui=await setup();const check=ui.document.querySelector('[data-home-visible="weather"]');check.checked=false;check.dispatchEvent(new ui.window.Event('change',{bubbles:true}));assert.equal(ui.$('home-widget-weather').hidden,true);ui.document.querySelector('[data-home-move="news"][data-direction="-1"]').click();assert.equal(ui.$('home-widgets').firstElementChild.id,'home-widget-news');const restored=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('home-widget-weather').hidden,true);assert.equal(restored.$('home-widgets').firstElementChild.id,'home-widget-news');const portable=vm.runInContext('JSON.stringify(collectBackup())',ui.context);await previewBackup(restored,portable);restored.$('backup-apply').click();assert.equal(restored.$('home-widget-weather').hidden,true);const old=JSON.parse(portable);delete old.preferences.homeLayout;delete old.savedNews;restored.context.oldText=JSON.stringify(old);assert.equal(vm.runInContext('validateBackup(JSON.parse(oldText)).preferences.homeLayout.every(row=>row.visible)',restored.context),true);ui.$('settings-reset').click();assert.equal(ui.$('home-widget-weather').hidden,false);assert.equal(ui.$('home-widgets').firstElementChild.id,'home-widget-weather');
});
test('saved headlines survive source updates, reload and JSON import, reject unsafe links and fail without losing data',async()=>{
 const ui=await setup({configure:d=>{d.baseballNews=ok([{title:'保存する記事 <script>',date:'2027-01-01',url:'https://npb.jp/news/2027/0101.html'}]);}});ui.$('baseball-news').querySelector('[data-news-save]').click();assert.equal(ui.$('saved-news-count').textContent,'1件');assert.equal(ui.$('saved-news-list').querySelector('script'),null);ui.data.baseballNews=ok([]);await vm.runInContext('refresh()',ui.context);assert.match(ui.$('saved-news-list').textContent,/保存する記事/);const restored=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('saved-news-count').textContent,'1件');const portable=vm.runInContext('JSON.stringify(collectBackup())',ui.context),other=await setup();await previewBackup(other,portable);other.$('backup-apply').click();assert.equal(other.$('saved-news-count').textContent,'1件');const bad=JSON.parse(portable);bad.savedNews[0].url='javascript:alert(1)';await previewBackup(other,JSON.stringify(bad));assert.match(other.$('backup-status').textContent,/保存ニュース/);restored.$('saved-news-list').querySelector('[data-news-save]').click();assert.equal(restored.$('saved-news-count').textContent,'0件');other.window.localStorage.setItem=()=>{throw Error('quota');};other.$('saved-news-list').querySelector('[data-news-save]').click();assert.equal(other.$('saved-news-count').textContent,'1件');assert.match(other.$('saved-news-status').textContent,/保存できません/);
});
test('draft lock prevents changes, persists per year and in JSON, allows live stats and deliberate unlocking',async()=>{
 const ui=await setup({configure:draftFixture});await fillDraft(ui);ui.$('draft-lock').click();assert.equal(ui.$('draft-lock').getAttribute('aria-pressed'),'true');assert.equal(ui.$('draft-name-a').disabled,true);assert.ok([...ui.$('draft-picks').querySelectorAll('input,select')].every(el=>el.disabled));pickDraftPlayer(ui,'hr',0,0,'巨','B1');assert.equal(vm.runInContext('draftState.picks.hr[0][0].name',ui.context),'A1');ui.change('draft-name-a','不正変更');assert.equal(ui.$('draft-name-a').value,'A軍');ui.data.draft.clubs['神'].bat.data[0].values.hr='12';await vm.runInContext('refresh()',ui.context);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),22);const restored=await setup({configure:draftFixture,saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('draft-lock').getAttribute('aria-pressed'),'true');assert.equal(vm.runInContext('collectBackup().drafts[2027].locked',ui.context),true);const target=await setup({configure:draftFixture});await previewBackup(target,vm.runInContext('JSON.stringify(collectBackup())',ui.context));target.$('backup-apply').click();assert.equal(target.$('draft-lock').getAttribute('aria-pressed'),'true');ui.change('draft-year-select','2028');assert.equal(ui.$('draft-lock').getAttribute('aria-pressed'),'false');ui.change('draft-year-select','2027');ui.$('draft-lock').click();assert.equal(ui.$('draft-name-a').disabled,false);pickDraftPlayer(ui,'hr',1,0,'','');pickDraftPlayer(ui,'hr',0,0,'巨','B1');assert.equal(vm.runInContext('draftState.picks.hr[0][0].name',ui.context),'B1');
});
test('comparison shows both armies at each round, rate direction, missing values and escaped names',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.year=2026;d.draft.clubs['巨'].bat.data[0].values.hr='2';}});await fillDraft(ui);ui.document.querySelector('[data-draft-view="compare"]').click();assert.equal(ui.$('draft-picks').hidden,true);assert.equal(ui.$('draft-comparison').hidden,false);assert.equal(ui.$('draft-comparison').querySelectorAll('.round-comparison').length,5);assert.match(ui.$('draft-comparison').textContent,/A1/);assert.match(ui.$('draft-comparison').textContent,/B1/);assert.match(ui.$('draft-comparison').textContent,/B軍が2本 上回る/);ui.context.compareTest=true;vm.runInContext("draftState.names[0]='<img src=x>';draftState.picks.era[0][0]={team:'神',name:'A1'};draftState.picks.era[1][0]={team:'巨',name:'B1'};draftState.picks.hr[0][0]=null;draftState.picks.hr[1][0]=null;draftCategory='era';paintDraft()",ui.context);assert.equal(ui.$('draft-comparison').querySelector('img'),null);assert.match(ui.$('draft-comparison').textContent,/低い/);assert.match(ui.$('draft-comparison').textContent,/比較待ち/);
});
test('regional warning is independent of hidden weather, shows issue/source times, explicit failure and stale data',async()=>{
 const ui=await setup({configure:d=>{d.daily={alerts:{'13':ok({items:[{name:'レベル3大雨警報',area:'東京地方',issuedAt:'2026-12-31T15:00:00Z'}]})}};}});assert.equal(ui.$('home-alerts').hidden,false);assert.match(ui.$('home-alerts').textContent,/大雨警報/);const check=ui.document.querySelector('[data-home-visible="weather"]');check.checked=false;check.dispatchEvent(new ui.window.Event('change',{bubbles:true}));assert.equal(ui.$('home-alerts').hidden,false);ui.data.daily.alerts['13'].data.items=[];await vm.runInContext('refresh()',ui.context);assert.equal(ui.$('home-alerts').hidden,true);ui.data.daily.alerts['13'].fetchedAt='2026-12-30T00:00:00Z';await vm.runInContext('refresh()',ui.context);assert.equal(ui.$('home-alerts').hidden,false);assert.match(ui.$('home-alerts').textContent,/2時間以上/);ui.data.daily.alerts['13']={ok:false};await vm.runInContext('refresh()',ui.context);assert.match(ui.$('home-alerts').textContent,/取得できていません/);
});
