import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';

const categories=[{id:'avg',label:'打率',unit:''},{id:'hr',label:'本塁打',unit:'本'},{id:'rbi',label:'打点',unit:'点'},{id:'w',label:'勝利',unit:'勝'},{id:'era',label:'防御率',unit:'',low:true},{id:'so',label:'奪三振',unit:'個'}];
const ok=data=>({ok:true,data,source:'https://npb.jp/',fetchedAt:'2026-12-31T16:00:00Z'});
const fixture=()=>({year:2027,today:'2027-01-01',generatedAt:'2026-12-31T16:00:00Z',categories,
 standings:ok({c:[{team:'阪神タイガース',wins:'80',losses:'60',draws:'3',pct:'.571',gap:'-'},{team:'読売ジャイアンツ',wins:'77',losses:'62',draws:'4',pct:'.554',gap:'2.5'}],p:[]}),
 baseballGames:ok([{date:'2026-12-28',home:'阪神',away:'巨人',status:'finished',time:'14:00',venue:'甲子園'},{date:'2027-01-01',home:'巨人',away:'DeNA',status:'scheduled',time:'14:00',venue:'東京ドーム'},{date:'2027-01-02',home:'阪神',away:'広島',status:'cancelled',time:'14:00',venue:'甲子園'},{date:'2027-01-04',home:'巨人',away:'阪神',status:'scheduled',time:'18:00',venue:'東京ドーム'}]),
 footballGames:ok([{date:'2027-01-03',opponent:'対戦国',status:'scheduled',url:'https://www.jfa.jp/',venue:'国立'}]),fifa:{ok:false},baseballNews:ok([]),footballNews:ok([]),
 leaders:Object.fromEntries(categories.map(c=>[c.id,{c:ok(c.id==='era'?[{name:'投手A',team:'神',league:'c',value:'1.80'},{name:'投手B',team:'巨',league:'c',value:'2.13'}]:[{name:'選手A',team:'神',league:'c',value:c.id==='avg'?'.320':'39'},{name:'選手B',team:'巨',league:'c',value:c.id==='avg'?'.297':'20'}]),p:ok([{name:'選手C',team:'西',league:'p',value:c.id==='era'?'1.60':c.id==='avg'?'.330':'45'}])}]))});
async function setup(options={}){
 const data=fixture();options.configure?.(data);const {window,document}=parseHTML(await readFile('public/index.html','utf8'));
 window.location={hash:''};window.history={pushState(_state,_title,url){window.location.hash=url;}};const storage=new Map(Object.entries(options.saved||{}));window.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k),key:i=>[...storage.keys()][i],get length(){return storage.size;}};
 Object.defineProperty(window.HTMLSelectElement.prototype,'options',{configurable:true,get(){return this.querySelectorAll('option');}});
 Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this._value??this.querySelector('option')?.getAttribute('value')??'';},set(v){this._value=v;}});
 class Clock extends Date{constructor(...args){super(...(args.length?args:['2026-12-31T16:00:00Z']));}static now(){return new Date('2026-12-31T16:00:00Z').getTime();}}
 const context=vm.createContext({window,document,Intl,Date:Clock,Number,String,Set,Math,AbortSignal,setInterval(){},fetch:async()=>({ok:true,json:async()=>data}),...options.globals});
 vm.runInContext(await readFile('public/app.js','utf8'),context);await new Promise(r=>setTimeout(r,0));
 return {data,context,document,window,storage,$:id=>document.getElementById(id),change:(id,value)=>{const el=document.getElementById(id);el.value=value;el.dispatchEvent(new window.Event('change'));}};
}
test('home uses Tokyo today and Monday to Sunday across the year boundary',async()=>{
 const {$}=await setup();assert.equal($('today-count').textContent,'1試合');assert.match($('today-games').textContent,/巨人 × DeNA/);assert.equal($('week-count').textContent,'4試合');assert.match($('week-games').textContent,/終了/);assert.match($('week-games').textContent,/中止・延期/);assert.match($('week-games').textContent,/対戦国/);assert.match($('week-range').textContent,/12月28日/);assert.match($('week-range').textContent,/1月3日/);assert.doesNotMatch($('week-games').textContent,/巨人 × 阪神/);
});
test('calendar filters include the selected day and follow favorite changes',async()=>{
 const {document,$,change}=await setup();const filter=value=>document.querySelector(`[data-calendar-filter="${value}"]`).click();
 filter('football');assert.equal($('calendar').querySelectorAll('.calendar-event.baseball').length,0);assert.equal($('calendar').querySelectorAll('.calendar-event.football').length,1);assert.doesNotMatch($('day-games').textContent,/巨人/);
 filter('favorite');assert.equal($('calendar').querySelectorAll('.calendar-event').length,0);assert.match($('calendar-filter-note').textContent,/応援球団を選ぶ/);
 change('favorite-team','巨');assert.equal($('calendar').querySelectorAll('.calendar-event.football').length,0);assert.equal($('calendar').querySelectorAll('.calendar-event').length,2);assert.match($('day-games').textContent,/巨人/);
 change('favorite-team','神');assert.doesNotMatch($('day-games').textContent,/巨人/);filter('baseball');assert.equal($('calendar').querySelectorAll('.calendar-event').length,3);filter('all');assert.equal($('calendar').querySelectorAll('.calendar-event').length,4);
});
test('title gaps compare team players with league leaders and preserve decimal precision',async()=>{
 const {document,$,change}=await setup();assert.match($('leaders').textContent,/0.023/);change('leader-team','巨');assert.match($('leaders').textContent,/リーグ首位との差/);assert.match($('leaders').textContent,/0.023/);
 document.querySelector('[data-category="hr"]').click();assert.match($('leaders').textContent,/19 本/);document.querySelector('[data-category="era"]').click();assert.match($('leaders').textContent,/0.33/);
 document.querySelector('#leader-tabs [data-league="all"]').click();assert.match($('leaders').textContent,/0.20/);assert.match($('leaders').textContent,/首位（差なし）/);
});
test('failed sources and absent qualified players do not become fabricated summaries',async()=>{
 const {data,context,$,change}=await setup();change('favorite-team','巨');data.standings.ok=false;data.baseballGames.ok=false;data.leaders.avg.c.data=[];data.leaders.hr.c.ok=false;await vm.runInContext('refresh()',context);
 assert.match($('home-schedule-note').textContent,/取得成功分のみ/);assert.equal($('today-count').textContent,'0試合');assert.equal($('week-count').textContent,'1試合');
});
test('favorite players are marked without filtering other teams and reset immediately',async()=>{
 const {$,document,change}=await setup();change('favorite-team','巨');assert.equal($('leaders').querySelectorAll('tbody tr').length,2);assert.equal($('leaders').querySelectorAll('.favorite-player').length,1);assert.match($('leaders').querySelector('.favorite-player').textContent,/選手B/);assert.match($('leaders').querySelector('.favorite-player-mark').getAttribute('aria-label'),/応援球団/);$('settings-reset').click();assert.equal($('leaders').querySelectorAll('.favorite-player').length,0);assert.ok(document.querySelector('.stat-help summary'));assert.match(document.querySelector('.stat-help').textContent,/引き分け/);
});
test('previous comparison ranks all players, handles corrections and missing baselines',async()=>{
 const {data,context,$,document}=await setup();
 data.previous=JSON.parse(JSON.stringify({year:data.year,generatedAt:'2026-12-31T15:00:00Z',standings:data.standings,leaders:data.leaders}));
 data.previous.standings.data.c.reverse();data.previous.standings.data.c[1].wins='79';
 data.previous.leaders.hr.c.data=[{name:'選手A',team:'神',league:'c',value:'38'},...Array.from({length:11},(_,i)=>({name:'別選手'+i,team:'神',league:'c',value:String(37-i)})),{name:'選手B',team:'巨',league:'c',value:'19'}];
 await vm.runInContext('refresh()',context);assert.match($('standings').textContent,/↑ 1位上昇/);assert.match($('standings').textContent,/勝 \+1/);assert.match($('comparison-time').textContent,/前回比の基準/);
 document.querySelector('[data-category="hr"]').click();assert.match($('leaders').textContent,/↑ 11位上昇/);assert.match($('leaders').textContent,/\+1 本/);
 data.leaders.hr.c.data[0].value='37';await vm.runInContext('refresh()',context);assert.match($('leaders').textContent,/-1 本/);
 data.previous.leaders.hr.c.ok=false;await vm.runInContext('refresh()',context);assert.match($('leaders').textContent,/比較なし/);
 data.previous.year=2026;await vm.runInContext('refresh()',context);assert.match($('comparison-time').textContent,/比較できる前回/);assert.match($('standings').textContent,/比較なし/);
});
test('next fixture simulation updates both opponents and handles unknown matches safely',async()=>{
 const {data,context,$,change}=await setup();data.fifa={ok:true,data:{date:'2026-12-01',rows:[{rank:1,code:'ESP',name:'Spain',points:1700},{rank:2,code:'BRA',name:'Brazil',points:1608},{rank:3,code:'JPN',name:'Japan',points:1600},{rank:4,code:'ARG',name:'Argentina',points:1599}]}};
 data.footballGames.data=[{date:'2027-01-04',opponent:'アルゼンチン',competition:'予選',status:'scheduled'},{date:'2027-01-02',opponent:'ブラジル',competition:'予選',status:'finished'},{date:'2027-01-03',opponent:'ブラジル',competition:'FIFAワールドカップ予選',status:'scheduled'}];
 await vm.runInContext('refresh()',context);assert.equal($('simulator').hidden,false);assert.match($('roadmap').textContent,/日本 × ブラジル/);assert.match($('roadmap').textContent,/1月3日/);assert.match($('opponent').textContent,/ブラジル/);assert.equal($('importance').value,'25');
 change('importance','10');const scenarios=$('simulation').querySelectorAll('.sim-result');assert.match(scenarios[0].textContent,/概算 2位/);assert.match(scenarios[2].textContent,/概算 4位/);assert.match(scenarios[0].textContent,/想定ポイントを超過/);
 data.footballGames.data[2].competition='大会種別未確定';await vm.runInContext('refresh()',context);assert.equal($('importance').value,'');assert.match($('simulation').textContent,/試合の種類を選ぶ/);
 data.footballGames.data[2].opponent='未定';await vm.runInContext('refresh()',context);assert.equal($('simulator').hidden,true);assert.match($('roadmap').textContent,/照合できない/);
 data.footballGames.ok=false;await vm.runInContext('refresh()',context);assert.match($('roadmap').textContent,/日程を取得できない/);
});
test('match weighting distinguishes confirmed windows, stages and unknown competitions',async()=>{
 const {context}=await setup();const importance=(competition,date='2026-11-14')=>vm.runInContext(`matchImportance(${JSON.stringify({competition,date})})`,context);
 assert.equal(importance('MIZUHO BLUE CHALLENGE'),'10');assert.equal(importance('国際親善試合','2026-11-18'),'5');assert.equal(importance('国際親善試合','2027-03-20'),'');assert.equal(importance('FIFAワールドカップ予選'),'25');assert.equal(importance('AFCアジアカップ グループステージ'),'35');assert.equal(importance('AFCアジアカップ 準々決勝'),'40');assert.equal(importance('FIFAワールドカップ 準々決勝'),'60');assert.equal(importance('FIFAワールドカップ'),'');assert.equal(importance('大会未定'),'');
});
test('font size persists alongside existing theme and favorite preferences',async()=>{
 const settings='sports-desk-preferences-v1';const ui=await setup({saved:{[settings]:JSON.stringify({theme:'green',favorite:'巨'})}});assert.equal(ui.document.documentElement.dataset.fontSize,'standard');ui.document.querySelector('#font-size-options [data-font-size="large"]').click();assert.equal(ui.document.documentElement.dataset.fontSize,'large');const value=JSON.parse(ui.storage.get(settings));assert.equal(value.theme,'green');assert.equal(value.favorite,'巨');assert.equal(value.fontSize,'large');
 const loaded=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(loaded.document.documentElement.dataset.fontSize,'large');assert.equal(loaded.document.querySelector('#font-size-options [data-font-size="large"]').getAttribute('aria-pressed'),'true');loaded.$('settings-reset').click();assert.equal(loaded.document.documentElement.dataset.fontSize,'standard');
});
test('recent results use favorite perspective, preserve zero scores and omit cancelled or future games',async()=>{
 const ui=await setup({configure:d=>{d.baseballResults=ok([{date:'2027-01-01',home:'巨人',away:'阪神',homeScore:0,awayScore:0,status:'finished'},...Array.from({length:5},(_,i)=>({date:`2026-12-${31-i}`,home:'阪神',away:'巨人',homeScore:3,awayScore:1,status:'finished'})),{date:'2027-01-03',home:'巨人',away:'阪神',homeScore:5,awayScore:0,status:'finished'},{date:'2027-01-01',home:'巨人',away:'阪神',status:'cancelled'}]);}});ui.change('favorite-team','巨');assert.equal(ui.$('baseball-results').querySelectorAll('.recent-result').length,5);assert.match(ui.$('baseball-results').textContent,/0 − 0/);assert.match(ui.$('baseball-results').textContent,/引き分け/);assert.match(ui.$('baseball-results').textContent,/負け/);assert.doesNotMatch(ui.$('baseball-results').textContent,/5 − 0/);
 ui.data.baseballResults.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('baseball-results').textContent,/取得できません/);
});
test('opponent profile shows official point gap and latest known head-to-head; PK score remains separate',async()=>{
 const ui=await setup({configure:d=>{
  d.fifa={ok:true,data:{date:'2026-12-01',rows:[{rank:1,code:'BRA',name:'Brazil',points:1700},{rank:2,code:'JPN',name:'Japan',points:1600}]}};
  d.footballGames=ok([{date:'2027-01-03',opponent:'ブラジル',status:'scheduled',competition:'親善試合'}]);d.footballHistory=ok([{date:'2026-12-30',opponent:'エクアドル',status:'finished',japanScore:0,opponentScore:0,score:'〇0-0 PK5-4',result:'win'},{date:'2026-12-20',opponent:'ブラジル',status:'finished',japanScore:1,opponentScore:2,score:'●1-2',result:'loss'},{date:'2027-01-04',opponent:'ブラジル',status:'finished',japanScore:9,opponentScore:0}]);
 }});assert.match(ui.$('football-result').textContent,/勝ち（PK戦）/);assert.match(ui.$('football-result').textContent,/0 − 0/);assert.match(ui.$('football-result').textContent,/PK5-4/);assert.match(ui.$('opponent-profile').textContent,/1位/);assert.match(ui.$('opponent-profile').textContent,/日本より 100.00 pts 上/);assert.match(ui.$('opponent-profile').textContent,/1 − 2/);assert.doesNotMatch(ui.$('opponent-profile').textContent,/9 − 0/);
 ui.data.footballHistory.data=[];await vm.runInContext('refresh()',ui.context);assert.match(ui.$('opponent-profile').textContent,/見つかりません/);ui.data.footballHistory.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('football-result').textContent,/取得できません/);
});

test('small font preference survives reload and keeps theme and favorite',async()=>{
 const ui=await setup();ui.change('favorite-team','巨');ui.document.querySelector('#font-size-options [data-font-size="small"]').click();assert.equal(ui.document.documentElement.dataset.fontSize,'small');const restored=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(restored.document.documentElement.dataset.fontSize,'small');assert.equal(restored.$('favorite-team').value,'巨');
});
test('news shows only three newest entries and calendar counts follow its filter',async()=>{
 const ui=await setup({configure:d=>{for(const sport of ['baseball','football'])d[sport+'News']=ok(Array.from({length:6},(_,i)=>({date:'2027-01-01',title:'News '+i,url:'https://npb.jp/'+i})));}});for(const sport of ['baseball','football'])assert.equal(ui.$(sport+'-news').querySelectorAll('a').length,3);const cell=ui.$('calendar').querySelector('[data-day="2027-01-01"]');assert.equal(cell.querySelector('.day-count.baseball').textContent,'⚾1');cell.click();assert.match(ui.$('day-games').textContent,/巨人/);assert.equal(ui.document.querySelector('.week-summary').hasAttribute('open'),false);assert.equal(ui.document.querySelector('#home .favorite-card'),null);
});

function draftFixture(d){
 d.draft={seasonComplete:false,clubs:{}};for(const [team,prefix] of [['神','A'],['巨','B']]){const players=Array.from({length:5},(_,i)=>({team,name:prefix+(i+1),values:{avg:prefix==='A'?'.300':'.280',hr:String(i),h:'100',rbi:'50',w:'10',era:prefix==='A'?'2.00':'3.00',sv:'0'}}));d.draft.clubs[team]={bat:ok(players),pit:ok(players)};}
 d.leaders.avg.c=ok(Object.values(d.draft.clubs).flatMap(c=>c.bat.data.map(p=>({...p,league:'c',value:p.values.avg}))));d.leaders.era.c=ok(Object.values(d.draft.clubs).flatMap(c=>c.pit.data.map(p=>({...p,league:'c',value:p.values.era}))));
}
async function fillDraft(ui,id='hr'){
 ui.document.querySelector(`#draft-categories [data-draft-category="${id}"]`).click();
 for(let army=0;army<2;army++)for(let round=0;round<5;round++)for(const [field,value] of [['team',army===0?'神':'巨'],['name',(army===0?'A':'B')+(round+1)]]){const el=ui.document.querySelector(`[data-draft-field="${field}"][data-army="${army}"][data-round="${round}"]`);el.value=value;el.dispatchEvent(new ui.window.Event('change',{bubbles:true}));}
}
test('draft has seven five-round departments, sums real zeros and persists names and picks',async()=>{
 const ui=await setup({configure:draftFixture});assert.equal(ui.$('draft-categories').querySelectorAll('button').length,7);assert.equal(ui.$('draft-picks').querySelectorAll('.draft-round').length,10);await fillDraft(ui);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),10);assert.match(ui.$('draft-picks').textContent,/現在の成績0本/);ui.change('draft-name-a','りり軍');const restored=await setup({configure:draftFixture,saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('draft-name-a').value,'りり軍');assert.match(restored.$('draft-overview').textContent,/引き分け/);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).ready',restored.context),true);
});
test('draft uses qualifying rate averages, ERA favors lower and missing data never becomes zero',async()=>{
 const ui=await setup({configure:draftFixture});await fillDraft(ui,'avg');assert.equal(vm.runInContext('draftTotal(draftCategories[0],0).value',ui.context),.3);assert.match(ui.$('draft-overview').textContent,/A軍 優勢/);ui.data.leaders.avg.c.data=ui.data.leaders.avg.c.data.filter(p=>p.name!=='A1');await vm.runInContext('refresh()',ui.context);assert.match(ui.$('draft-picks').textContent,/規定未達/);assert.equal(vm.runInContext('draftTotal(draftCategories[0],0).count',ui.context),4);await fillDraft(ui,'era');assert.equal(vm.runInContext('draftDecision(draftCategories[5],draftTotal(draftCategories[5],0),draftTotal(draftCategories[5],1))',ui.context),0);ui.data.draft.clubs['神'].pit.ok=false;await vm.runInContext('refresh()',ui.context);assert.match(ui.$('draft-picks').textContent,/取得失敗/);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).value',ui.context),null);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).ready',ui.context),false);
});
test('draft blocks duplicate picks, updates fetched stats and starts a separate season',async()=>{
 const ui=await setup({configure:draftFixture});await fillDraft(ui);const duplicate=ui.document.querySelector('[data-draft-field="name"][data-army="0"][data-round="1"]');duplicate.value='A1';duplicate.dispatchEvent(new ui.window.Event('change',{bubbles:true}));assert.match(ui.$('draft-save-status').textContent,/指名済み/);assert.equal(vm.runInContext('draftState.picks.hr[0][1].name',ui.context),'A2');ui.data.draft.clubs['神'].bat.data[0].values.hr='12';await vm.runInContext('refresh()',ui.context);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),22);ui.data.year=2028;await vm.runInContext('refresh()',ui.context);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).selected',ui.context),0);assert.ok(ui.storage.has('sports-desk-draft-v1-2027'));
});
test('draft only declares final comparison when all departments are ready and handles blocked storage',async()=>{
 const ui=await setup({configure:draftFixture});ui.data.draft.seasonComplete=true;for(const id of ['avg','hr','h','rbi','w','era','sv'])await fillDraft(ui,id);await vm.runInContext('refresh()',ui.context);assert.match(ui.$('draft-score').textContent,/最終比較/);assert.match(ui.$('draft-score').textContent,/A軍 2勝/);assert.match(ui.$('draft-score').textContent,/引分 5/);ui.window.localStorage.setItem=()=>{throw Error('blocked');};ui.change('draft-name-a','<img src=x>');assert.match(ui.$('draft-save-status').textContent,/保存できません/);assert.equal(ui.$('draft-overview').querySelector('img'),null);assert.match(ui.$('draft-overview').textContent,/<img src=x>/);
});

test('menu collapses and reopens, persists independently, and update time lives in header',async()=>{
 const ui=await setup();assert.equal(ui.$('data-updated').closest('header').classList.contains('topbar'),true);assert.match(ui.$('data-updated').textContent,/データ取得・集計完了/);assert.equal(ui.$('favorite-summary'),null);assert.equal(ui.$('site-menu').hidden,false);ui.$('menu-toggle').click();assert.equal(ui.$('site-menu').hidden,true);assert.equal(ui.$('menu-toggle').getAttribute('aria-expanded'),'false');assert.match(ui.$('menu-toggle').getAttribute('aria-label'),/開く/);const restored=await setup({saved:Object.fromEntries(ui.storage)});assert.equal(restored.$('site-menu').hidden,true);restored.$('menu-toggle').click();assert.equal(restored.$('site-menu').hidden,false);assert.equal(restored.$('menu-toggle').getAttribute('aria-expanded'),'true');restored.window.localStorage.setItem=()=>{throw Error('blocked');};restored.$('menu-toggle').click();assert.equal(restored.$('site-menu').hidden,true);
});

function searchDraft(ui,query,army=0,round=0){const input=ui.document.querySelector(`[data-draft-search][data-army="${army}"][data-round="${round}"]`);input.value=query;input.dispatchEvent(new ui.window.Event('input',{bubbles:true}));return ui.$(`draft-player-${army}-${round}`);}
async function previewBackup(ui,text,size=new Blob([text]).size){Object.defineProperty(ui.$('backup-file'),'files',{configurable:true,value:[{name:'backup.json',size,text:async()=>text}]});ui.$('backup-file').dispatchEvent(new ui.window.Event('change'));await new Promise(r=>setTimeout(r,0));}
test('draft search filters live, normalizes full-width names and preserves a selected player with no matches',async()=>{
 const ui=await setup({configure:draftFixture});await fillDraft(ui);assert.equal(searchDraft(ui,'Ａ ２').querySelectorAll('option').length,3);assert.match(ui.$('draft-player-0-0').textContent,/A2/);assert.equal(ui.$('draft-player-0-0').value,'A1');assert.match(ui.$('draft-player-0-0').querySelector('[value="A2"]').getAttribute('disabled'),/^$/);searchDraft(ui,'存在しない名前');assert.equal(ui.$('draft-player-0-0').value,'A1');assert.match(ui.$('draft-picks').querySelector('[data-search-count="0-0"]').textContent,/0人/);assert.equal(vm.runInContext('draftState.picks.hr[0][0].name',ui.context),'A1');const team=ui.document.querySelector('[data-draft-field="team"][data-army="0"][data-round="0"]');team.value='巨';team.dispatchEvent(new ui.window.Event('change',{bubbles:true}));assert.equal(ui.document.querySelector('[data-draft-search][data-army="0"][data-round="0"]').value,'');assert.equal(ui.$('draft-player-0-0').value,'');
});
test('JSON export downloads all saved seasons with preferences but no official statistics or unrelated keys',async()=>{
 const blobs=new Map(),downloads=[];let revoked=false;const ui=await setup({configure:draftFixture,globals:{Blob,URL:{createObjectURL(blob){blobs.set('blob:backup',blob);return 'blob:backup';},revokeObjectURL(){revoked=true;}},setTimeout(callback){callback();}}});await fillDraft(ui);ui.change('draft-name-a','移行する軍');ui.change('favorite-team','巨');ui.document.querySelector('#font-size-options [data-font-size="small"]').click();ui.$('menu-toggle').click();const old=vm.runInContext('JSON.stringify(draftState)',ui.context);ui.storage.set('sports-desk-draft-v1-2026',old);ui.storage.set('unrelated-secret','must-not-export');ui.document.createElement=(original=>function(tag){const el=original.call(this,tag);if(tag==='a')el.click=()=>downloads.push({href:el.href,filename:el.download});return el;})(ui.document.createElement);ui.$('backup-export').click();assert.equal(downloads.length,1);assert.match(downloads[0].filename,/sports-desk-backup-.*\.json/);const exported=JSON.parse(await blobs.get('blob:backup').text());assert.equal(exported.preferences.favorite,'巨');assert.equal(exported.preferences.fontSize,'small');assert.equal(exported.menuCollapsed,true);assert.equal(Object.keys(exported.drafts).length,2);assert.equal(exported.drafts['2027'].names[0],'移行する軍');assert.doesNotMatch(JSON.stringify(exported),/must-not-export|generatedAt|leaders/);assert.equal(revoked,true);
});
test('JSON import previews before mutation, restores another browser and preserves years absent from file',async()=>{
 const source=await setup({configure:draftFixture});await fillDraft(source);source.change('draft-name-a','引継ぎ軍');source.change('favorite-team','神');source.$('menu-toggle').click();const text=vm.runInContext('JSON.stringify(collectBackup())',source.context);const target=await setup({configure:draftFixture});target.storage.set('sports-desk-draft-v1-2025',vm.runInContext('JSON.stringify(emptyDraft())',target.context));await previewBackup(target,text);assert.equal(target.$('backup-preview').hidden,false);assert.match(target.$('backup-preview-text').textContent,/引継ぎ軍/);assert.equal(target.$('favorite-team').value,'all');target.$('backup-apply').click();assert.equal(target.$('favorite-team').value,'神');assert.equal(target.$('site-menu').hidden,true);assert.equal(target.$('draft-name-a').value,'引継ぎ軍');assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',target.context),10);assert.ok(target.storage.has('sports-desk-draft-v1-2025'));assert.equal(target.$('backup-preview').hidden,true);const reloaded=await setup({configure:draftFixture,saved:Object.fromEntries(target.storage)});assert.equal(reloaded.$('draft-name-a').value,'引継ぎ軍');assert.equal(reloaded.$('favorite-team').value,'神');
});
test('JSON validation rejects malformed, oversized, unsupported, duplicate and prototype-key data without writes',async()=>{
 const ui=await setup({configure:draftFixture});const good=JSON.parse(vm.runInContext('JSON.stringify(collectBackup())',ui.context));const before=JSON.stringify([...ui.storage]);for(const bad of ['{broken',JSON.stringify({...good,version:99}),JSON.stringify({...good,preferences:{...good.preferences,theme:'unknown'}}),JSON.stringify({...good,drafts:{'../../x':good.drafts['2027']}}),JSON.stringify(good).replace('"drafts":{','"drafts":{"__proto__":{},')]){await previewBackup(ui,bad);assert.equal(ui.$('backup-preview').hidden,true);assert.match(ui.$('backup-status').textContent,/読み込めません/);assert.equal(JSON.stringify([...ui.storage]),before);}await previewBackup(ui,JSON.stringify(good),1024*1024+1);assert.match(ui.$('backup-status').textContent,/1MB/);const duplicate=structuredClone(good);duplicate.drafts['2027'].picks.hr[0][0]={team:'神',name:'A1'};duplicate.drafts['2027'].picks.hr[1][0]={team:'神',name:'A1'};await previewBackup(ui,JSON.stringify(duplicate));assert.match(ui.$('backup-status').textContent,/重複指名/);assert.equal(JSON.stringify([...ui.storage]),before);
});
test('JSON cancel and storage failure keep existing selections and preferences',async()=>{
 const source=await setup({configure:draftFixture});await fillDraft(source);source.change('favorite-team','巨');const text=vm.runInContext('JSON.stringify(collectBackup())',source.context);const ui=await setup({configure:draftFixture});ui.change('favorite-team','神');const before=JSON.stringify([...ui.storage]);await previewBackup(ui,text);ui.$('backup-cancel').click();ui.$('backup-apply').click();assert.equal(ui.$('favorite-team').value,'神');assert.equal(JSON.stringify([...ui.storage]),before);await previewBackup(ui,text);const original=ui.window.localStorage.setItem;let writes=0;ui.window.localStorage.setItem=(key,value)=>{if(++writes===3)throw Error('quota');return original(key,value);};ui.$('backup-apply').click();assert.match(ui.$('backup-status').textContent,/保存できません/);assert.equal(JSON.stringify([...ui.storage]),before);assert.equal(ui.$('favorite-team').value,'神');assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).selected',ui.context),0);
});

function uiHistory(d,year=2027){const rows=Object.entries(d.draft.clubs).flatMap(([team,club])=>club.bat.data.map(p=>[team,p.name,p.values.avg,p.values.hr,p.values.h,p.values.rbi,p.values.w,p.values.era,p.values.sv,true,true]));const feb=rows.map(row=>row.map((value,i)=>i===3?String(Number(value)+2):value));return {version:1,seasons:{[year]:{latestMonth:year+'-02',months:{[year+'-01']:{generatedAt:year+'-01-31T10:00:00Z',rows,seasonComplete:false},[year+'-02']:{generatedAt:year+'-02-28T10:00:00Z',rows:feb,seasonComplete:true}}}}};}
test('monthly view shows cumulative totals, consecutive-month changes and explicitly unrecorded months',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.draftHistory=uiHistory(d);}});await fillDraft(ui);const rows=ui.$('draft-monthly').querySelectorAll('tbody tr');assert.equal(rows.length,12);assert.match(rows[0].textContent,/10/);assert.match(rows[1].textContent,/20/);assert.match(rows[1].textContent,/\+10 本/);assert.match(rows[2].textContent,/未記録/);delete ui.data.draftHistory.seasons['2027'].months['2027-01'];await vm.runInContext('refresh()',ui.context);assert.doesNotMatch(ui.$('draft-monthly').querySelectorAll('tbody tr')[1].textContent,/\+10 本/);
});
test('year selector separates saved picks, uses archived season stats and never substitutes future stats',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.draftHistory=uiHistory(d,2026);}});await fillDraft(ui);ui.change('draft-name-a','2027軍');ui.change('draft-year-select','2026');await fillDraft(ui);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),20);ui.change('draft-name-a','2026軍');ui.change('draft-year-select','2028');await fillDraft(ui);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),null);assert.match(ui.$('draft-picks').textContent,/年度成績未公開/);ui.change('draft-year-select','2027');assert.equal(ui.$('draft-name-a').value,'2027軍');assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),10);ui.change('draft-year-select','2026');assert.equal(ui.$('draft-name-a').value,'2026軍');assert.ok(ui.storage.has('sports-desk-draft-v1-2028'));ui.change('draft-year-select','2028');ui.data.year=2028;await vm.runInContext('refresh()',ui.context);assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',ui.context),10);
});
test('2026 ERA special Imai pick is unmeasurable, excluded from average, portable, and forbidden in other categories or years',async()=>{
 const ui=await setup({configure:d=>{draftFixture(d);d.year=2026;}});await fillDraft(ui,'era');for(const [field,value] of [['team','MLB'],['name','今井 達也']]){const el=ui.document.querySelector(`[data-draft-field="${field}"][data-army="0"][data-round="0"]`);el.value=value;el.dispatchEvent(new ui.window.Event('change',{bubbles:true}));}assert.match(ui.$('draft-picks').textContent,/計測不可/);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).count',ui.context),4);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).value',ui.context),2);assert.equal(vm.runInContext('draftTotal(draftCategories[5],0).ready',ui.context),true);const backup=vm.runInContext('JSON.stringify(validateBackup(collectBackup()))',ui.context);const loaded=await setup({configure:d=>{draftFixture(d);d.year=2026;},saved:Object.fromEntries(ui.storage)});assert.equal(vm.runInContext('draftState.picks.era[0][0].name',loaded.context),'今井 達也');const parsed=JSON.parse(backup);parsed.drafts['2027']=parsed.drafts['2026'];delete parsed.drafts['2026'];ui.context.badBackup=JSON.stringify(parsed);assert.throws(()=>vm.runInContext('validateBackup(JSON.parse(badBackup))',ui.context));ui.document.querySelector('#draft-categories [data-draft-category="hr"]').click();assert.equal(ui.document.querySelector('[data-draft-field="team"] [value="MLB"]'),null);
});
