import {load} from 'cheerio';
const clean=value=>String(value??'').replace(/\s+/g,' ').trim();
const key=value=>clean(value).normalize('NFKC').replace(/\s/g,'');
const jfaLink=value=>{try{const u=new URL(value,'https://www.jfa.jp');return u.origin==='https://www.jfa.jp'?u.href:null;}catch{return null;}};
async function safely(work,source){try{return {ok:true,data:await work(),source,fetchedAt:new Date().toISOString()};}catch{return {ok:false,source,error:'公開元から取得できませんでした。'};}}
export function parseSquadDirectory(html,today){const $=load(html);const entries=$('a').filter((_,e)=>/招集メンバー/.test($(e).text())).map((_,e)=>{const row=$(e).closest('tr').text(),m=row.match(/(?:(20\d\d)[/年])?(\d{1,2})[\/月](\d{1,2})/);return {url:jfaLink($(e).attr('href')),date:m?`${m[1]||today.slice(0,4)}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''};}).get().filter(e=>e.url&&e.date&&e.date<=today);return entries.sort((a,b)=>b.date.localeCompare(a.date)).filter((e,i,all)=>all.findIndex(v=>v.url===e.url)===i).slice(0,2);}
export function parseSquad(html){const $=load(html);const players=$('.competition-member a[href*="/samuraiblue/member/"]').map((_,e)=>{const a=$(e),name=clean(a.find('.name').text()).replace(/^\d+\s*/,''),position=clean(a.closest('.section-block').find('h4').first().text());return {id:a.attr('href').split('/').pop().replace('.html',''),name,position,club:clean(a.find('.status').text()),url:jfaLink(a.attr('href'))};}).get().filter(p=>p.name&&/^(GK|DF|MF|FW)/.test(p.position));if(players.length<11)throw Error('Squad structure changed');return [...new Map(players.map(p=>[p.id,p])).values()];}
export function parseProgram(html){const $=load(html);const baseline=$('body').text().match(/(20\d\d)年(\d+)月(\d+)日現在/);const asOf=baseline?`${baseline[1]}-${baseline[2].padStart(2,'0')}-${baseline[3].padStart(2,'0')}`:null;const players=$('.player_card').map((_,e)=>{const card=$(e);const value=card.find('dt').filter((_,d)=>/国際Aマッチ試合数/.test($(d).text())).next('dd').text().match(/(\d+)試合\s*[／/]\s*(-?\d+)得点/);const position=clean(card.find('.pos').first().text());return {name:clean(card.find('.name').first().text()),caps:value?Number(value[1]):null,goals:value&&position!=='GK'?Number(value[2]):null,conceded:value&&position==='GK'?Math.abs(Number(value[2])):null,asOf};}).get();const events=[];$('.game_line').each((_,e)=>{$(e).find('li').each((_,row)=>{const minute=clean($(row).find('.timer').text()),player=clean($(row).find('.pointer').text());if(minute&&player)events.push({minute,player,kind:'得点',team:$(e).hasClass('left')?'日本':'相手'});});});$('.modal_report [data-tablist]').each((_,e)=>{$(e).find('.member_list li').each((_,row)=>{const change=clean($(row).find('.change').text()),m=change.match(/(\d+(?:\+\d+)?')\s*(IN|OUT)/);if(m)events.push({minute:m[1],player:clean($(row).find('.name').text()),kind:m[2]==='IN'?'交代 IN':'交代 OUT',team:$(e).attr('data-tablist')==='jp'?'日本':'相手'});});});return {players,events:events.sort((a,b)=>parseInt(a.minute)-parseInt(b.minute)),asOf};}
export function parseStarters(html,year){const $=load(html),heading=clean($('.contents h4').first().text()),m=heading.match(/(\d+)月(\d+)日/);if(!m)throw Error('Starter date missing');const date=`${year}-${m[1].padStart(2,'0')}-${m[2].padStart(2,'0')}`;return {date,games:$('.unit_starter_position .unit').map((_,e)=>({info:clean($(e).find('.info').text()),pitchers:['left','right'].map(side=>({team:clean($(e).find('.team_'+side+' img').attr('alt')),name:clean($(e).find('.team_'+side+' span').text())}))})).get()};}
const clubAliases={'ル・アーヴルAC':'Le Havre AC','KRCゲンク':'KRC Genk','アストン・ビラ':'Aston Villa','シントトロイデンVV':'Sint-Truidense','ボルシア・メンヘングラートバッハ':'Borussia Mönchengladbach','フェイエノールト':'Feyenoord','FCコペンハーゲン':'FC Copenhagen','フライブルク':'SC Freiburg','SCフライブルク':'SC Freiburg','クリスタル・パレス':'Crystal Palace','スタッド・ランス':'Stade de Reims','レアル・ソシエダ':'Real Sociedad','アイントラハト・フランクフルト':'Eintracht Frankfurt','リーズ・ユナイテッド':'Leeds United','マインツ05':'Mainz','LOSCリール':'Lille','オリンピック・リヨン':'Lyon','サウサンプトンFC':'Southampton','イプスウィッチ・タウン':'Ipswich Town','PSVアイントホーフェン':'PSV Eindhoven','VfLヴォルフスブルク':'VfL Wolfsburg','バレンシアCF':'Valencia','シャルケ04':'Schalke 04','KVCウェステルロー':'KVC Westerlo','ブライトン・アンド・ホーヴ・アルビオン':'Brighton & Hove Albion','リヴァプール':'Liverpool','セルティック':'Celtic','バイエルン・ミュンヘン':'Bayern Munich','FCザンクトパウリ':'St. Pauli','トッテナム・ホットスパー':'Tottenham Hotspur'};
export function parseClubBoard(payload){if(!Array.isArray(payload.events))throw Error('Scoreboard changed');return payload.events.map(event=>{const c=event.competitions?.[0],teams=c?.competitors,status=c?.status?.type;if(!/^\d+$/.test(String(event.id))||teams?.length!==2||!Number.isFinite(Date.parse(event.date)))return null;const side=where=>{const t=teams.find(t=>t.homeAway===where);const value=typeof t?.score==='object'?t.score.value:t?.score;return {name:t?.team?.displayName||'',score:status?.completed&&value!==''&&value!==null&&value!==undefined&&Number.isFinite(Number(value))?Number(value):null};};return {id:event.id,kickoff:event.date,date:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date(event.date)),home:side('home'),away:side('away'),status:status?.completed?'finished':status?.state==='in'?'inprogress':'scheduled',url:`https://www.espn.com/soccer/match/_/gameId/${event.id}`};}).filter(Boolean);}
export async function collectClubWeek(getText,league,months,from,to){
 const batches=await Promise.all(months.map(async month=>parseClubBoard(JSON.parse(await getText(`https://site.api.espn.com/apis/site/v2/sports/soccer/${league}/scoreboard?dates=${month}&limit=1000`)))));
 return [...new Map(batches.flat().map(game=>[game.id,game])).values()].filter(game=>game.date>=from&&game.date<=to);
}
// Soccer scoreboards accept a month, not a hyphenated date range.
// Fetch only the one or two months touched by this week and filter in JST.
export async function collectEnhancements(getText,{today,year,footballGames}){
 const rosterSource=`https://www.jfa.jp/samuraiblue_${year}/member/`;
 const [footballSquad,baseballStarters]=await Promise.all([safely(async()=>{const entries=parseSquadDirectory(await getText(rosterSource),today);if(!entries.length)throw Error('No squad');const current=entries[0],players=parseSquad(await getText(current.url));let prior=null;try{if(entries[1])prior={...entries[1],players:parseSquad(await getText(entries[1].url))};}catch{}const finished=footballGames?.ok?footballGames.data.filter(g=>g.status==='finished'&&g.date<=today).sort((a,b)=>b.date.localeCompare(a.date)):[];const latest=finished[0];let program=null;const programSource=latest?`https://op.jfa.jp/samuraiblue${latest.date.replaceAll('-','')}/`:null;try{if(programSource)program=parseProgram(await getText(programSource));}catch{}return {date:current.date,url:current.url,players:players.map(p=>({...p,...(program?.players.find(v=>key(v.name)===key(p.name))||{}) ,name:p.name})),previous:prior,timeline:latest?{date:latest.date,opponent:latest.opponent,events:program?.events||[],source:programSource,ok:!!program?.events.length}:null,statsSource:programSource,statsAsOf:program?.asOf};},rosterSource),safely(async()=>parseStarters(await getText('https://npb.jp/announcement/starter/'),year),'https://npb.jp/announcement/starter/')]);
 const overseas=await safely(async()=>{if(!footballSquad.ok)throw Error('No squad');const start=new Date(today+'T00:00:00Z');start.setUTCDate(start.getUTCDate()-((start.getUTCDay()+6)%7));const from=start.toISOString().slice(0,10);start.setUTCDate(start.getUTCDate()+6);const to=start.toISOString().slice(0,10),months=[...new Set([from.slice(0,7),to.slice(0,7)])].map(month=>month.replace('-',''));const boards=[],leagues=['eng.1','eng.2','ger.1','ger.2','esp.1','fra.1','ita.1','ned.1','bel.1','por.1','sco.1','den.1'];for(let i=0;i<leagues.length;i+=4)boards.push(...await Promise.all(leagues.slice(i,i+4).map(league=>safely(async()=>collectClubWeek(getText,league,months,from,to),'https://www.espn.com/soccer/scoreboard'))));if(boards.every(b=>!b.ok))throw Error('All leagues unavailable');const weekGames=[...new Map(boards.filter(s=>s.ok).flatMap(s=>s.data).map(game=>[game.id,game])).values()];const players=footballSquad.data.players.filter(p=>p.club.includes('／')).map(p=>{const club=p.club.split('／')[0],alias=clubAliases[club];return {id:p.id,name:p.name,club:p.club,matched:!!alias,games:alias?weekGames.filter(g=>[g.home.name,g.away.name].some(n=>key(n)===key(alias))):[]};});return {from,to,coverage:'現在の招集選手のうち海外所属者。欧州主要12リーグのリーグ戦掲載分（カップ戦を除く）。出場有無は含みません。',failedLeagues:boards.filter(b=>!b.ok).length,players};},'https://www.espn.com/soccer/scoreboard');
 return {footballSquad,baseballStarters,overseas};
}
export function captureFifaHistory(previous,current){const history=Array.isArray(previous?.fifaHistory)?previous.fifaHistory.filter(s=>s?.date&&Array.isArray(s.rows)):[];if(current.fifa?.ok&&current.fifa.data?.date&&Array.isArray(current.fifa.data.rows)){const snapshot={date:current.fifa.data.date,rows:current.fifa.data.rows.map(({code,rank,points})=>({code,rank,points}))};const found=history.find(s=>s.date===snapshot.date);if(found)Object.assign(found,snapshot);else history.push(snapshot);}return history.sort((a,b)=>a.date.localeCompare(b.date)).slice(-120);}
