import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
const data=JSON.parse(await readFile(process.argv[2]||'/tmp/sports-result.json','utf8'));
const {document,window}=parseHTML(await readFile('public/index.html','utf8'));
window.location={hash:''};
const saved=new Map();window.localStorage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k),key:i=>[...saved.keys()][i],get length(){return saved.size;}};
window.history={pushState(state,title,url){window.location.hash=url;}};
// linkedom omits the writable select.value/options browser contract.
Object.defineProperty(window.HTMLSelectElement.prototype,'options',{get(){return this.querySelectorAll('option');}});
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._selection??this.querySelector('option')?.getAttribute('value')??'';},set(v){this._selection=v;}});
const context=vm.createContext({document,window,console,Intl,URL,Date,Number,String,Set,Math,AbortSignal,setInterval(){},fetch:async()=>({ok:true,json:async()=>data})});
vm.runInContext(await readFile('public/app.js','utf8'),context);
await new Promise(r=>setTimeout(r,30));
const $=id=>document.getElementById(id);
assert.equal($('home').hidden,false);assert.equal($('baseball').hidden,true);assert.equal($('football').hidden,true);assert.equal($('guide').hidden,true);
document.querySelector('.sidebar-help').click();assert.equal($('guide').hidden,false);assert.equal($('baseball').hidden,true);assert.equal($('tab-guide'),null);
document.querySelector('#guide [data-open-tab="football"]').click();assert.equal($('football').hidden,false);assert.equal($('guide').hidden,true);assert.equal(window.location.hash,'#football');
$('tab-baseball').click();assert.equal($('baseball').hidden,false);
assert.match($('standings').textContent,/阪神/);
assert.equal($('standings').querySelectorAll('tbody tr').length,6);
document.querySelector('#standings-tabs [data-league="p"]').click();
assert.match($('standings').textContent,/ソフトバンク/);
document.querySelector('#leader-tabs [data-league="all"]').click();
assert.match($('leader-spotlight').textContent,/レイエス/);
assert.match($('leaders').textContent,/セ/);assert.match($('leaders').textContent,/パ/);
document.querySelector('#categories [data-category="era"]').click();
assert.match($('leader-spotlight').textContent,/平良/);
assert.match($('baseball-games').textContent,/巨人/);
$('team').value='西武';$('team').dispatchEvent(new window.Event('change'));
assert.match($('baseball-games').textContent,/西武/);assert.doesNotMatch($('baseball-games').textContent,/巨人/);
assert.match($('football-game').textContent,/ブラジル/);
assert.match($('fifa-summary').textContent,/pts/);assert.equal($('simulator').hidden,false);
const before=$('simulation').textContent;$('importance').value='25';$('importance').dispatchEvent(new window.Event('change'));assert.notEqual($('simulation').textContent,before);
const failures=[data.standings,data.baseballGames,data.footballGames,data.fifa,data.baseballNews,data.footballNews,data.baseballResults,data.footballHistory,...Object.values(data.leaders).flatMap(v=>[v.c,v.p])].filter(s=>!s.ok);
assert.equal(failures.length,0,'All official data sources must succeed');
assert.match($('data-updated').textContent,/データ取得・集計完了/);assert.match(document.querySelector('[data-time="standings"]').textContent,/取得：/);
assert.equal($('calendar').querySelectorAll('[data-day]').length,31);assert.match($('calendar').textContent,/⚾/);assert.match($('calendar').textContent,/⚽/);
$('month-next').click();assert.match($('calendar-month').textContent,/11月/);assert.equal($('calendar').querySelectorAll('[data-day]').length,30);$('month-today').click();
$('calendar').querySelector('[data-day="2026-10-10"]').click();assert.match($('day-games').textContent,/巨人/);
$('favorite-team').value='西';$('favorite-team').dispatchEvent(new window.Event('change'));assert.equal($('team').value,'西武');assert.ok($('calendar').querySelector('.favorite'));assert.match(saved.get('sports-desk-preferences-v1'),/西/);
document.querySelector('[data-theme-choice="green"]').click();assert.equal(document.documentElement.dataset.theme,'green');assert.match(saved.get('sports-desk-preferences-v1'),/green/);
$('leader-team').value='西';$('leader-team').dispatchEvent(new window.Event('change'));assert.match($('leader-spotlight').textContent,/平良/);assert.ok([...$('leaders').querySelectorAll('tbody tr')].every(r=>r.textContent.includes('西')));assert.match($('leader-note').textContent,/球団内/);
$('leader-team').value='all';$('leader-team').dispatchEvent(new window.Event('change'));
for(const sport of ['baseball','football']){assert.equal($(sport+'-news').querySelectorAll('a').length,3);assert.match($(sport+'-news').textContent,/2026/);}
assert.equal($('baseball-results').querySelectorAll('.recent-result').length,5);
assert.match($('opponent-profile').textContent,/ブラジル/);assert.match($('football-result').textContent,/2 − 1/);
assert.equal($('play'),null);assert.equal($('tab-play'),null);
$('settings-reset').click();assert.equal(document.documentElement.dataset.theme,'lavender');assert.equal($('team').value,'all');assert.equal(document.documentElement.dataset.fontSize,undefined);assert.equal($('font-size-options'),null);
document.querySelector('#leader-tabs [data-league="all"]').click();
data.fifa.ok=false;data.leaders.era.c.ok=false;data.baseballNews.ok=false;
await vm.runInContext('refresh()',context);assert.equal($('simulator').hidden,true);assert.match($('status').textContent,/取得できません/);assert.match($('leaders').textContent,/取得できません/);assert.match($('baseball-news').textContent,/ニュースを取得できません/);
console.log('PASS: calendar month and day selection, favorite, themes and persistence, club rankings, news failures, official sources, both standings, combined ranking, ERA order, team filter, FIFA simulator, failure display.');

$('tab-draft').click();assert.equal($('draft').hidden,false);assert.equal($('draft-categories').querySelectorAll('button').length,7);assert.equal($('draft-picks').querySelectorAll('.draft-round').length,10);
const club=Object.keys(data.draft.clubs)[0],player=data.draft.clubs[club].bat.data[0];document.querySelector('#draft-categories [data-draft-category="hr"]').click();for(const [field,value] of [['team',club],['name',player.name]]){const el=document.querySelector(`[data-draft-field="${field}"][data-army="0"][data-round="0"]`);el.value=value;el.dispatchEvent(new window.Event('change',{bubbles:true}));}assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).value',context),Number(player.values.hr));assert.equal(vm.runInContext('draftTotal(draftCategories[1],0).ready',context),false);assert.match($('draft-score').textContent,/判定待ち/);console.log('PASS: real club statistics, draft selection, zero totals and incomplete verdict.');

const search=document.querySelector('[data-draft-search][data-army="0"][data-round="0"]');search.value=player.name;search.dispatchEvent(new window.Event('input',{bubbles:true}));assert.match($('draft-player-0-0').textContent,new RegExp(player.name));assert.equal($('draft-player-0-0').value,player.name);const backup=vm.runInContext('JSON.stringify(validateBackup(collectBackup()))',context);assert.equal(JSON.parse(backup).format,'japan-sports-desk-backup');assert.equal(JSON.parse(backup).drafts[String(data.year)].picks.hr[0][0].name,player.name);console.log('PASS: real player search and portable JSON structure.');
assert.ok(document.querySelector('#draft-year-select [value="2027"]'));assert.ok(document.querySelector('#draft-year-select [value="2028"]'));assert.ok(data.draftHistory.seasons[String(data.year)]);assert.equal($('draft-monthly').querySelectorAll('tbody tr').length,12);assert.match($('draft-monthly').textContent,/未記録/);const historySize=Object.keys(data.draftHistory.seasons[String(data.year)].months).length;assert.ok(historySize>=1&&historySize<=12);console.log('PASS: year selection and monthly published archive.');

assert.equal(data.daily.regions.length,47);assert.equal($('national-news').querySelectorAll('a').length,3);assert.equal($('local-news').querySelectorAll('a').length,3);assert.ok($('home-weather').querySelector('.weather-day'));$('home-region').value='27';$('home-region').dispatchEvent(new window.Event('change'));assert.match($('weather-heading').textContent,/大阪府/);assert.equal($('settings-region').value,'27');assert.equal($('local-news-source').href,'https://news.yahoo.co.jp/media/kantele');assert.ok(data.footballRivals.ok);data.fifa.ok=true;await vm.runInContext('refresh()',context);assert.equal($('football-rivals').querySelectorAll('details').length,3);document.querySelector('[data-rivals-scope="all"]').click();assert.equal($('football-rivals').querySelectorAll('details').length,data.fifa.data.rows.filter(r=>r.rank<data.fifa.data.rows.find(r=>r.code==='JPN').rank).length);assert.ok($('football-rivals').querySelector('.rival-match'));assert.match($('draft-picks').textContent,new RegExp(player.name));console.log('PASS: real weather, national/regional news, full draft names and higher-ranked national fixtures/results.');
assert.equal(Object.keys(data.daily.alerts).length,47);assert.ok(Object.values(data.daily.alerts).every(source=>source.ok));const selectedAlerts=data.daily.alerts['27'];assert.equal($('home-alerts').hidden,selectedAlerts.data.items.length===0);
const weatherVisible=document.querySelector('[data-home-visible="weather"]');weatherVisible.checked=false;weatherVisible.dispatchEvent(new window.Event('change',{bubbles:true}));assert.equal($('home-widget-weather').hidden,true);document.querySelector('[data-home-move="news"][data-direction="-1"]').click();assert.equal($('home-widgets').firstElementChild.id,'home-widget-news');
const saveNews=$('national-news').querySelector('[data-news-save]');assert.ok(saveNews);saveNews.click();assert.equal($('saved-news-count').textContent,'1件');$('draft-lock').click();assert.equal($('draft-lock').getAttribute('aria-pressed'),'true');assert.ok([...$('draft-picks').querySelectorAll('input,select')].every(el=>el.disabled));document.querySelector('[data-draft-view="compare"]').click();assert.equal($('draft-comparison').querySelectorAll('.round-comparison').length,5);assert.match($('draft-comparison').textContent,new RegExp(player.name));const personalized=JSON.parse(vm.runInContext('JSON.stringify(validateBackup(collectBackup()))',context));assert.equal(personalized.savedNews.length,1);assert.equal(personalized.preferences.homeLayout[0].id,'news');assert.equal(personalized.drafts[data.year].locked,true);vm.runInContext('applyBackup(validateBackup(collectBackup()))',context);assert.equal($('saved-news-count').textContent,'1件');assert.equal($('draft-lock').getAttribute('aria-pressed'),'true');console.log('PASS: real regional alerts, reordered/hidden home widgets, saved Yahoo headline, portable draft lock and comparison.');
