import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
const data=JSON.parse(await readFile(process.argv[2]||'/tmp/sports-result.json','utf8'));
const {document,window}=parseHTML(await readFile('public/index.html','utf8'));
window.location={hash:''};
const saved=new Map();window.localStorage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,v)};
window.history={pushState(state,title,url){window.location.hash=url;}};
// linkedom omits the writable select.value/options browser contract.
Object.defineProperty(window.HTMLSelectElement.prototype,'options',{get(){return this.querySelectorAll('option');}});
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._selection??this.querySelector('option')?.getAttribute('value')??'';},set(v){this._selection=v;}});
const context=vm.createContext({document,window,console,Intl,Date,Number,String,Set,Math,AbortSignal,setInterval(){},fetch:async()=>({ok:true,json:async()=>data})});
vm.runInContext(await readFile('public/app.js','utf8'),context);
await new Promise(r=>setTimeout(r,30));
const $=id=>document.getElementById(id);
assert.equal($('home').hidden,false);assert.equal($('baseball').hidden,true);assert.equal($('football').hidden,true);assert.equal($('guide').hidden,true);
document.querySelector('.sidebar-help').click();assert.equal($('guide').hidden,false);assert.equal($('baseball').hidden,true);assert.equal($('tab-guide'),null);
document.querySelector('#guide [data-open-tab="football"]').click();assert.equal($('football').hidden,false);assert.equal($('guide').hidden,true);assert.equal(window.location.hash,'#football');
$('tab-baseball').click();assert.equal($('baseball').hidden,false);
assert.match($('standings').textContent,/阪神/);
assert.equal($('standings').querySelectorAll('tbody tr').length,6);
document.querySelector('#standings-tabs [data-league="p"]').click();
assert.match($('standings').textContent,/ソフトバンク/);
document.querySelector('#leader-tabs [data-league="all"]').click();
assert.match($('leader-spotlight').textContent,/レイエス/);
assert.match($('leaders').textContent,/セ/);assert.match($('leaders').textContent,/パ/);
document.querySelector('#categories [data-category="era"]').click();
assert.match($('leader-spotlight').textContent,/平良/);
assert.match($('baseball-games').textContent,/巨人/);
$('team').value='西武';$('team').dispatchEvent(new window.Event('change'));
assert.match($('baseball-games').textContent,/西武/);assert.doesNotMatch($('baseball-games').textContent,/巨人/);
assert.match($('football-game').textContent,/ブラジル/);
assert.match($('fifa-summary').textContent,/pts/);assert.equal($('simulator').hidden,false);
const before=$('simulation').textContent;$('importance').value='25';$('importance').dispatchEvent(new window.Event('change'));assert.notEqual($('simulation').textContent,before);
const failures=[data.standings,data.baseballGames,data.footballGames,data.fifa,data.baseballNews,data.footballNews,data.baseballResults,data.footballHistory,...Object.values(data.leaders).flatMap(v=>[v.c,v.p])].filter(s=>!s.ok);
assert.equal(failures.length,0,'All official data sources must succeed');
assert.match($('data-updated').textContent,/データ取得・集計完了/);assert.match(document.querySelector('[data-time="standings"]').textContent,/取得：/);
assert.equal($('calendar').querySelectorAll('[data-day]').length,31);assert.match($('calendar').textContent,/⚾/);assert.match($('calendar').textContent,/⚽/);
$('month-next').click();assert.match($('calendar-month').textContent,/11月/);assert.equal($('calendar').querySelectorAll('[data-day]').length,30);$('month-today').click();
$('calendar').querySelector('[data-day="2026-10-10"]').click();assert.match($('day-games').textContent,/巨人/);
$('favorite-team').value='西';$('favorite-team').dispatchEvent(new window.Event('change'));assert.equal($('team').value,'西武');assert.ok($('calendar').querySelector('.favorite'));assert.match(saved.get('sports-desk-preferences-v1'),/西/);
document.querySelector('[data-theme-choice="green"]').click();assert.equal(document.documentElement.dataset.theme,'green');assert.match(saved.get('sports-desk-preferences-v1'),/green/);
$('leader-team').value='西';$('leader-team').dispatchEvent(new window.Event('change'));assert.match($('leader-spotlight').textContent,/平良/);assert.ok([...$('leaders').querySelectorAll('tbody tr')].every(r=>r.textContent.includes('西')));assert.match($('leader-note').textContent,/球団内/);
$('leader-team').value='all';$('leader-team').dispatchEvent(new window.Event('change'));
for(const sport of ['baseball','football']){assert.equal($(sport+'-news').querySelectorAll('a').length,6);assert.match($(sport+'-news').textContent,/2026/);}
assert.equal($('baseball-results').querySelectorAll('.recent-result').length,5);
assert.match($('opponent-profile').textContent,/ブラジル/);assert.match($('football-result').textContent,/2 − 1/);
$('tab-play').click();assert.equal($('play').hidden,false);assert.equal($('baseball').hidden,true);$('draw-player').click();assert.ok($('lottery-result').querySelector('.picked-player'));assert.ok($('lottery-result').querySelectorAll('.pick-stats>div').length>0);
for(const i of [0,1,2])document.querySelector(`[data-bingo-cell="${i}"]`).click();assert.match($('bingo-status').textContent,/BINGO/);$('reset-bingo').click();assert.match($('bingo-status').textContent,/1\/9/);
document.querySelector('#font-size-options [data-font-size="large"]').click();assert.equal(document.documentElement.dataset.fontSize,'large');
$('settings-reset').click();assert.equal(document.documentElement.dataset.theme,'lavender');assert.equal($('team').value,'all');assert.equal(document.documentElement.dataset.fontSize,'standard');
document.querySelector('#leader-tabs [data-league="all"]').click();
data.fifa.ok=false;data.leaders.era.c.ok=false;data.baseballNews.ok=false;
await vm.runInContext('refresh()',context);assert.equal($('simulator').hidden,true);assert.match($('status').textContent,/取得できません/);assert.match($('leaders').textContent,/取得できません/);assert.match($('baseball-news').textContent,/ニュースを取得できません/);
console.log('PASS: calendar month and day selection, favorite, themes and persistence, club rankings, news failures, official sources, both standings, combined ranking, ERA order, team filter, FIFA simulator, failure display.');
