import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
const data=JSON.parse(await readFile(process.argv[2]||'/tmp/sports-result.json','utf8'));
const {document,window}=parseHTML(await readFile('public/index.html','utf8'));
// linkedom omits the writable select.value/options browser contract.
Object.defineProperty(window.HTMLSelectElement.prototype,'options',{get(){return this.querySelectorAll('option');}});
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._selection??this.querySelector('option')?.getAttribute('value')??'';},set(v){this._selection=v;}});
const context=vm.createContext({document,console,Intl,Date,Number,String,Set,Math,AbortSignal,setInterval(){},fetch:async()=>({ok:true,json:async()=>data})});
vm.runInContext(await readFile('public/app.js','utf8'),context);
await new Promise(r=>setTimeout(r,30));
const $=id=>document.getElementById(id);
assert.match($('standings').textContent,/阪神/);
assert.equal($('standings').querySelectorAll('tbody tr').length,6);
document.querySelector('#standings-tabs [data-league="p"]').click();
assert.match($('standings').textContent,/ソフトバンク/);
document.querySelector('#leader-tabs [data-league="all"]').click();
assert.match($('leader-spotlight').textContent,/レイエス/);
assert.match($('leaders').textContent,/セ/);assert.match($('leaders').textContent,/パ/);
document.querySelector('#categories [data-category="era"]').click();
assert.match($('leader-spotlight').textContent,/平良/);
assert.match($('baseball-games').textContent,/巨人/);
$('team').value='西武';$('team').dispatchEvent(new window.Event('change'));
assert.match($('baseball-games').textContent,/西武/);assert.doesNotMatch($('baseball-games').textContent,/巨人/);
assert.match($('football-game').textContent,/ブラジル/);
assert.match($('fifa-summary').textContent,/pts/);assert.equal($('simulator').hidden,false);
const before=$('simulation').textContent;$('importance').value='25';$('importance').dispatchEvent(new window.Event('change'));assert.notEqual($('simulation').textContent,before);
const failures=[data.standings,data.baseballGames,data.footballGames,data.fifa,...Object.values(data.leaders).flatMap(v=>[v.c,v.p])].filter(s=>!s.ok);
assert.equal(failures.length,0,'All official data sources must succeed');
data.fifa.ok=false;data.leaders.era.c.ok=false;
await vm.runInContext('refresh()',context);assert.equal($('simulator').hidden,true);assert.match($('status').textContent,/取得できません/);assert.match($('leaders').textContent,/取得できません/);
console.log('PASS: official sources, both standings, combined ranking, ERA order, team filter, FIFA simulator, failure display.');
